package metrics

import (
	"fmt"
	"time"

	"github.com/confluentinc/kcp/internal/build_info"
	"github.com/confluentinc/kcp/internal/services/markdown"
	"github.com/confluentinc/kcp/internal/types"
	"github.com/confluentinc/kcp/internal/utils"
)

type ReportService interface {
	ProcessState(state types.State) types.ProcessedState
	FilterClusterMetrics(processedState types.ProcessedState, clusterArn string, sourceType string, startTime, endTime *time.Time) (*types.ProcessedClusterMetrics, error)
}

type MetricReporterOpts struct {
	ClusterIds []string
	State      *types.State
	StartDate  *time.Time
	EndDate    *time.Time
	SourceType string
}

type MetricReporter struct {
	reportService ReportService

	clusterIds []string
	state      *types.State
	startDate  *time.Time
	endDate    *time.Time
	sourceType string
}

func NewMetricReporter(reportService ReportService, opts MetricReporterOpts) *MetricReporter {
	return &MetricReporter{
		reportService: reportService,

		clusterIds: opts.ClusterIds,
		state:      opts.State,
		startDate:  opts.StartDate,
		endDate:    opts.EndDate,
		sourceType: opts.SourceType,
	}
}

func (r *MetricReporter) Run() error {
	fmt.Printf("🔍 Processing clusters: %v (from %s to %s)\n", r.clusterIds, r.startDate.Format("2006-01-02"), r.endDate.Format("2006-01-02"))

	processedState := r.reportService.ProcessState(*r.state)
	processedClusterMetrics := []types.ProcessedClusterMetrics{}

	// find the clusters in the state

	for _, clusterId := range r.clusterIds {
		clusterMetrics, err := r.reportService.FilterClusterMetrics(processedState, clusterId, r.sourceType, r.startDate, r.endDate)
		if err != nil {
			return fmt.Errorf("failed to filter cluster metrics: %v", err)
		}
		processedClusterMetrics = append(processedClusterMetrics, *clusterMetrics)
	}

	fileName := fmt.Sprintf("metric_report_%s.md", time.Now().Format("2006-01-02_15-04-05"))
	markdownReport := r.generateReport(processedClusterMetrics)
	if err := markdownReport.Print(markdown.PrintOptions{ToTerminal: false, ToFile: fileName}); err != nil {
		return fmt.Errorf("failed to write markdown report: %v", err)
	}

	return nil
}

func (r *MetricReporter) generateReport(clusters []types.ProcessedClusterMetrics) *markdown.Markdown {
	md := markdown.New()

	// Determine report title based on cluster types
	title := r.determineReportTitle(clusters)
	md.AddHeading(title, 1)

	// Add build info metadata for diagnostics in smaller italic text
	md.AddParagraph(fmt.Sprintf("*Generated by kcp (version: %s, commit: %s, built: %s)*",
		build_info.Version,
		build_info.Commit,
		build_info.Date))
	md.AddParagraph("")

	md.AddParagraph(fmt.Sprintf("**Report Period:** %s to %s",
		r.startDate.Format("2006-01-02"),
		r.endDate.Format("2006-01-02")))

	if len(r.clusterIds) > 0 {
		md.AddParagraph("**Clusters included in report:**")
		for _, clusterId := range r.clusterIds {
			md.AddParagraph(fmt.Sprintf("- %s", clusterId))
		}
	}

	md.AddHorizontalRule()

	// Process each cluster in this region
	for i, clusterMetrics := range clusters {

		if i > 0 {
			md.AddHorizontalRule()
		}
		r.addClusterSection(md, clusterMetrics)
	}

	md.AddHorizontalRule()

	return md
}

// determineReportTitle determines the report title based on cluster types
func (r *MetricReporter) determineReportTitle(clusters []types.ProcessedClusterMetrics) string {
	hasMSK := false
	hasOSK := false

	for _, cluster := range clusters {
		if r.isMSKCluster(cluster.ClusterArn) {
			hasMSK = true
		} else {
			hasOSK = true
		}
	}

	// Mixed MSK+OSK
	if hasMSK && hasOSK {
		return "Kafka Metrics Report"
	}
	// Only OSK clusters
	if hasOSK {
		return "OSK Metrics Report"
	}
	// Only MSK clusters (default)
	return "AWS MSK Metrics Report"
}

// isMSKCluster checks if a cluster identifier is an MSK ARN
func (r *MetricReporter) isMSKCluster(clusterArn string) bool {
	return len(clusterArn) > 4 && clusterArn[:4] == "arn:"
}

func (r *MetricReporter) addClusterSection(md *markdown.Markdown, clusterMetrics types.ProcessedClusterMetrics) {
	isMSK := r.isMSKCluster(clusterMetrics.ClusterArn)

	// Add cluster heading and identifier
	if isMSK {
		md.AddHeading(fmt.Sprintf("Cluster Name: %s", utils.ExtractClusterNameFromArn(clusterMetrics.ClusterArn)), 3)
		md.AddParagraph(fmt.Sprintf("**Cluster ARN**: %s", clusterMetrics.ClusterArn))
		md.AddParagraph(fmt.Sprintf("**Region**: %s", clusterMetrics.Region))
	} else {
		// OSK cluster - show ID instead of ARN
		md.AddHeading(fmt.Sprintf("Cluster: %s", clusterMetrics.ClusterArn), 3)
		md.AddParagraph(fmt.Sprintf("**Cluster ID**: %s", clusterMetrics.ClusterArn))

		// Add OSK-specific metadata
		environment := clusterMetrics.Environment
		if environment == "" {
			environment = "Not specified"
		}
		md.AddParagraph(fmt.Sprintf("**Environment**: %s", environment))

		location := clusterMetrics.Location
		if location == "" {
			location = "Not specified"
		}
		md.AddParagraph(fmt.Sprintf("**Location**: %s", location))
	}

	// Common fields
	md.AddParagraph(fmt.Sprintf("**Number of Broker Nodes**: %d", clusterMetrics.Metadata.NumberOfBrokerNodes))
	md.AddParagraph(fmt.Sprintf("**Kafka Version**: %s", clusterMetrics.Metadata.KafkaVersion))

	// MSK-specific fields
	if isMSK {
		md.AddParagraph(fmt.Sprintf("**Cluster Type**: %s", clusterMetrics.Metadata.ClusterType))
		md.AddParagraph(fmt.Sprintf("**Enhanced Monitoring**: %s", clusterMetrics.Metadata.EnhancedMonitoring))
		md.AddParagraph(fmt.Sprintf("**Instance Type**: %s", clusterMetrics.Metadata.InstanceType))
		md.AddParagraph(fmt.Sprintf("**Tiered Storage**: %t", clusterMetrics.Metadata.TieredStorage))
	}

	// Common metric period
	md.AddParagraph(fmt.Sprintf("**Period**: %d seconds", clusterMetrics.Metadata.Period))

	// MSK-specific advanced settings
	if isMSK {
		md.AddParagraph(fmt.Sprintf("**Follower Fetching**: %t", clusterMetrics.Metadata.FollowerFetching))
	}

	// Add metric aggregates
	if len(clusterMetrics.Aggregates) > 0 {
		md.AddHeading("Metric Aggregates", 4)

		headers := []string{"Metric", "Average", "Maximum", "Minimum"}
		var tableData [][]string

		for metricName, aggregate := range clusterMetrics.Aggregates {
			row := []string{
				metricName,
				r.formatMetricValue(aggregate.Average),
				r.formatMetricValue(aggregate.Maximum),
				r.formatMetricValue(aggregate.Minimum),
			}
			tableData = append(tableData, row)
		}

		if len(tableData) > 0 {
			md.AddTable(headers, tableData)
		}
	} else {
		md.AddParagraph("*No metric aggregates available for this cluster.*")
	}

	// Add individual metric values
	r.addIndividualMetricsSection(md, clusterMetrics.Metrics)

	// Add query details (MSK only)
	if isMSK {
		r.addQueryDetailsSection(md, clusterMetrics.QueryInfo)
	}
}

func (r *MetricReporter) addIndividualMetricsSection(md *markdown.Markdown, metrics []types.ProcessedMetric) {
	if len(metrics) == 0 {
		md.AddParagraph("*No individual metric data available for this cluster.*")
		return
	}

	md.AddHeading("Individual Metric Values", 4)

	// Group metrics by label (metric type)
	metricGroups := r.groupMetricsByLabel(metrics)

	for metricLabel, metricValues := range metricGroups {
		md.AddHeading(metricLabel, 5)

		if len(metricValues) == 0 {
			md.AddParagraph("*No data points available for this metric.*")
			continue
		}

		// Create table for this metric type
		headers := []string{"Start Time", "End Time", "Value"}
		var tableData [][]string

		for _, metric := range metricValues {
			startTime := r.formatTimestamp(metric.Start)
			endTime := r.formatTimestamp(metric.End)
			value := r.formatMetricValue(metric.Value)

			row := []string{startTime, endTime, value}
			tableData = append(tableData, row)
		}

		if len(tableData) > 0 {
			md.AddTable(headers, tableData)
		}

		// Add some spacing between metric types
		md.AddParagraph("")
	}
}

func (r *MetricReporter) groupMetricsByLabel(metrics []types.ProcessedMetric) map[string][]types.ProcessedMetric {
	groups := make(map[string][]types.ProcessedMetric)

	for _, metric := range metrics {
		groups[metric.Label] = append(groups[metric.Label], metric)
	}

	return groups
}

func (r *MetricReporter) addQueryDetailsSection(md *markdown.Markdown, queryInfos []types.MetricQueryInfo) {
	if len(queryInfos) == 0 {
		return
	}

	md.AddHeading("Query Details", 4)

	for _, info := range queryInfos {
		md.AddHeading(info.MetricName, 5)
		md.AddParagraph(fmt.Sprintf("**Namespace:** %s", info.Namespace))
		md.AddParagraph(fmt.Sprintf("**Dimensions:** %s", info.Dimensions))
		md.AddParagraph(fmt.Sprintf("**Statistic:** %s", info.Statistic))
		md.AddParagraph(fmt.Sprintf("**Period:** %d seconds", info.Period))

		if info.SearchExpression != "" {
			md.AddParagraph("**SEARCH Expression:**")
			md.AddCodeBlock(info.SearchExpression, "")
		}

		if info.MathExpression != "" {
			md.AddParagraph(fmt.Sprintf("**Aggregation:** `%s`", info.MathExpression))
		}

		if info.AWSCLICommand != "" {
			md.AddParagraph("**AWS CLI Command:**")
			md.AddCodeBlock(info.AWSCLICommand, "bash")
		}

		md.AddParagraph(fmt.Sprintf("*%s*", info.AggregationNote))
		md.AddParagraph("")
	}
}

func (r *MetricReporter) formatTimestamp(timestamp string) string {
	if timestamp == "" {
		return "N/A"
	}

	// Try parsing with RFC3339 first (handles timezone offsets like +01:00 from OSK metrics)
	if parsedTime, err := time.Parse(time.RFC3339, timestamp); err == nil {
		return parsedTime.Format("2006-01-02 15:04 MST")
	}

	// Fall back to MSK format without timezone
	if parsedTime, err := time.Parse("2006-01-02T15:04:05Z", timestamp); err == nil {
		return parsedTime.Format("2006-01-02 15:04 UTC")
	}

	// If parsing fails, return the original timestamp
	return timestamp
}

func (r *MetricReporter) formatMetricValue(value *float64) string {
	if value == nil {
		return "N/A"
	}
	return fmt.Sprintf("%.2f", *value)
}
