//go:build e2e

package cutover_test

import (
	"bufio"
	"context"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/client-go/dynamic"
	"k8s.io/client-go/kubernetes"
	"k8s.io/client-go/tools/clientcmd"
)

// Scenario names. Each scenario maps to a dedicated set of resources
// (source topic, cluster link, gateway CR) provisioned by setup.sh so that
// tests are fully isolated and do not depend on execution order.
const (
	scenarioBaseline                 = "baseline"                    // TestCutoverE2E
	scenarioPauseSyncHappy           = "pause-sync-happy"            // TestCutoverE2E_PauseOffsetSync_HappyPath
	scenarioPauseSyncRefuses         = "pause-sync-refuses"          // TestCutoverE2E_PauseOffsetSync_InitRefuses
	scenarioPauseSyncRestoresFilters = "pause-sync-restores-filters" // TestCutoverE2E_PauseOffsetSync_RestoresFilters
	scenarioBatch                    = "batch"                       // TestCutoverE2E_PromoteBatchSize
)

// envConfig holds connection details loaded from the .env file generated by
// setup.sh, resolved for a specific scenario.
type envConfig struct {
	Kubeconfig        string // host kubeconfig for assertions
	KubeContext       string
	Namespace         string
	SourceBootstrap   string
	DestBootstrap     string
	RestProxyEndpoint string
	DestClusterID     string
	ClusterAPIKey     string
	ClusterAPISecret  string
	KCPPod            string // pod running the kcp binary
	KubePath          string // in-pod kubeconfig path

	// Per-scenario resources.
	Scenario        string
	ClusterLinkName string
	TopicName       string   // single-topic scenarios (producer/consumer target)
	TopicNames      []string // all mirror topics for the scenario (>=1)
	GatewayName     string
	FencedCR        string // in-pod fixture path
	SwitchoverCR    string // in-pod fixture path
}

func loadEnvConfig(t *testing.T, scenario string) envConfig {
	t.Helper()

	envFile := filepath.Join(testdataDir(), ".env")
	f, err := os.Open(envFile)
	require.NoError(t, err, "failed to open .env file — did you run 'make test-cutover-setup'?")
	defer f.Close()

	vars := map[string]string{}
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		parts := strings.SplitN(line, "=", 2)
		if len(parts) == 2 {
			vars[parts[0]] = parts[1]
		}
	}
	require.NoError(t, scanner.Err())

	// Sanity-check the scenario was provisioned by setup.sh.
	provisioned := strings.Split(vars["KCP_E2E_SCENARIOS"], ",")
	found := false
	for _, s := range provisioned {
		if s == scenario {
			found = true
			break
		}
	}
	require.True(t, found, "scenario %q not provisioned by setup.sh (KCP_E2E_SCENARIOS=%q)", scenario, vars["KCP_E2E_SCENARIOS"])

	// Per-scenario env-var prefix: lowercase-dash -> UPPERCASE_UNDERSCORE.
	prefix := "KCP_E2E_" + strings.ReplaceAll(strings.ToUpper(scenario), "-", "_") + "_"

	// TopicNames comes from the comma-separated <PREFIX>TOPIC_NAMES var when
	// present (multi-topic scenarios); otherwise it falls back to the single
	// TOPIC_NAME so every scenario exposes a non-empty list.
	topicName := vars[prefix+"TOPIC_NAME"]
	var topicNames []string
	if names := vars[prefix+"TOPIC_NAMES"]; names != "" {
		topicNames = strings.Split(names, ",")
	} else if topicName != "" {
		topicNames = []string{topicName}
	}

	return envConfig{
		Kubeconfig:        vars["KCP_E2E_KUBECONFIG"],
		KubeContext:       vars["KCP_E2E_KUBE_CONTEXT"],
		Namespace:         vars["KCP_E2E_NAMESPACE"],
		SourceBootstrap:   vars["KCP_E2E_SOURCE_BOOTSTRAP"],
		DestBootstrap:     vars["KCP_E2E_DEST_BOOTSTRAP"],
		RestProxyEndpoint: vars["KCP_E2E_REST_PROXY_ENDPOINT"],
		DestClusterID:     vars["KCP_E2E_DEST_CLUSTER_ID"],
		ClusterAPIKey:     vars["KCP_E2E_CLUSTER_API_KEY"],
		ClusterAPISecret:  vars["KCP_E2E_CLUSTER_API_SECRET"],
		KCPPod:            vars["KCP_E2E_KCP_POD"],
		KubePath:          vars["KCP_E2E_KUBE_PATH"],

		Scenario:        scenario,
		ClusterLinkName: vars[prefix+"CLUSTER_LINK_NAME"],
		TopicName:       topicName,
		TopicNames:      topicNames,
		GatewayName:     vars[prefix+"GATEWAY_NAME"],
		FencedCR:        vars[prefix+"FENCED_CR"],
		SwitchoverCR:    vars[prefix+"SWITCHOVER_CR"],
	}
}

func testdataDir() string {
	// integration-tests/cutover/ -> integration-tests/cutover/testdata/
	return filepath.Join("testdata")
}

// runKCP executes the kcp binary inside the runner pod via kubectl exec.
func runKCP(t *testing.T, cfg envConfig, args ...string) (string, string, error) {
	t.Helper()

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Minute)
	defer cancel()

	kubectlArgs := []string{
		"--context", cfg.KubeContext,
		"-n", cfg.Namespace,
		"exec", cfg.KCPPod, "--",
		"/workspace/kcp",
	}
	kubectlArgs = append(kubectlArgs, args...)

	cmd := exec.CommandContext(ctx, "kubectl", kubectlArgs...)
	var stdout, stderr strings.Builder
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr

	err := cmd.Run()
	return stdout.String(), stderr.String(), err
}

// readPodFile reads a file from inside the runner pod.
func readPodFile(t *testing.T, cfg envConfig, podPath string) []byte {
	t.Helper()

	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	cmd := exec.CommandContext(ctx, "kubectl",
		"--context", cfg.KubeContext,
		"-n", cfg.Namespace,
		"exec", cfg.KCPPod, "--",
		"cat", podPath)
	var stderr strings.Builder
	cmd.Stderr = &stderr
	out, err := cmd.Output()
	require.NoError(t, err, "failed to read %s from pod: %s", podPath, stderr.String())
	return out
}

// gatewayGVR is the GroupVersionResource for Confluent Gateway CRs.
var gatewayGVR = schema.GroupVersionResource{
	Group:    "platform.confluent.io",
	Version:  "v1beta1",
	Resource: "gateways",
}

func getGatewayCR(t *testing.T, dynClient dynamic.Interface, namespace, name string) *unstructured.Unstructured {
	t.Helper()

	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	cr, err := dynClient.Resource(gatewayGVR).Namespace(namespace).Get(ctx, name, metav1.GetOptions{})
	require.NoError(t, err, "failed to get Gateway CR %s/%s", namespace, name)

	return cr
}

func getGatewayPodUIDs(t *testing.T, clientset kubernetes.Interface, namespace, gatewayName string) map[string]struct{} {
	t.Helper()

	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	pods, err := clientset.CoreV1().Pods(namespace).List(ctx, metav1.ListOptions{
		LabelSelector: fmt.Sprintf("app=%s", gatewayName),
	})
	require.NoError(t, err)

	uids := make(map[string]struct{}, len(pods.Items))
	for _, pod := range pods.Items {
		uids[string(pod.UID)] = struct{}{}
	}
	return uids
}

// cutoverState mirrors the state file structure for assertion purposes.
type cutoverState struct {
	Cutovers []cutoverConfig `json:"cutovers"`
}

type cutoverConfig struct {
	CutoverID                      string            `json:"cutover_id"`
	CurrentState                   string            `json:"current_state"`
	PauseConsumerOffsetSync        bool              `json:"pause_consumer_offset_sync"`
	PauseConsumerOffsetSyncFlipped bool              `json:"pause_consumer_offset_sync_flipped"`
	ClusterLinkConfigs             map[string]string `json:"cluster_link_configs"`
}

// runInPodBackground starts a command inside the runner pod and returns
// immediately. The caller is responsible for terminating it via killInPod or
// waiting for the configured duration to elapse. Output is captured into
// /workspace/<basename>.log inside the pod for post-mortem inspection.
func runInPodBackground(t *testing.T, cfg envConfig, logName string, command ...string) {
	t.Helper()

	cmdline := strings.Join(command, " ")
	bgScript := fmt.Sprintf("(%s >/workspace/%s.log 2>&1 &)", cmdline, logName)

	out, err := runInPod(t, cfg, 30*time.Second, "sh", "-c", bgScript)
	if err != nil {
		t.Fatalf("failed to start background command %q: %v\n%s", cmdline, err, out)
	}
}

// killInPod terminates a process by name inside the runner pod. Ignored if the
// process is not running (the test may have already let it exit naturally).
func killInPod(t *testing.T, cfg envConfig, processName string) {
	t.Helper()
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	_ = exec.CommandContext(ctx, "kubectl",
		"--context", cfg.KubeContext,
		"-n", cfg.Namespace,
		"exec", cfg.KCPPod, "--",
		"pkill", "-f", processName,
	).Run()
}

// runInPod executes a command synchronously inside the runner pod and returns
// combined stdout/stderr plus any error.
func runInPod(t *testing.T, cfg envConfig, timeout time.Duration, command ...string) (string, error) {
	t.Helper()

	ctx, cancel := context.WithTimeout(context.Background(), timeout)
	defer cancel()

	args := []string{
		"--context", cfg.KubeContext,
		"-n", cfg.Namespace,
		"exec", cfg.KCPPod, "--",
	}
	args = append(args, command...)

	out, err := exec.CommandContext(ctx, "kubectl", args...).CombinedOutput()
	return string(out), err
}

// setClusterLinkConfig calls the in-pod setconfig helper to PUT a config
// value on the cluster link. Used by InitRefuses to flip the offset-sync
// setting without depending on curl (busybox wget cannot do PUT).
func setClusterLinkConfig(t *testing.T, cfg envConfig, name, value string) {
	t.Helper()
	out, err := runInPod(t, cfg, 30*time.Second,
		"/workspace/setconfig",
		"--url", cfg.RestProxyEndpoint,
		"--cluster", cfg.DestClusterID,
		"--link", cfg.ClusterLinkName,
		"--name", name,
		"--value", value,
		"--op", "SET",
	)
	require.NoError(t, err, "setconfig %s=%s failed:\n%s", name, value, out)
}

// getClusterLinkOffsetSyncEnable fetches the cluster link's
// consumer.offset.sync.enable value via the Kafka REST proxy reachable from
// inside the cluster. Returns the literal string ("true", "false", or "" if
// the key is missing). Used by tests to observe transitions during execute.
func getClusterLinkOffsetSyncEnable(t *testing.T, cfg envConfig) string {
	t.Helper()
	return getClusterLinkConfig(t, cfg, "consumer.offset.sync.enable")
}

// getClusterLinkOffsetSyncEnableSoft is the goroutine-safe variant: it
// returns (value, error) instead of calling require on a *testing.T. Use
// this inside background goroutines — Go's testing package documents
// FailNow/require as unsafe outside the test goroutine.
func getClusterLinkOffsetSyncEnableSoft(cfg envConfig) (string, error) {
	return getClusterLinkConfigSoft(cfg, "consumer.offset.sync.enable")
}

// getClusterLinkConfig is the generic variant: returns the value for any
// config key on the cluster link, or "" if missing.
func getClusterLinkConfig(t *testing.T, cfg envConfig, name string) string {
	t.Helper()
	v, err := getClusterLinkConfigSoft(cfg, name)
	require.NoError(t, err)
	return v
}

// getClusterLinkConfigSoft is the goroutine-safe generic variant. Returns
// (value, error) so callers can use it inside background goroutines without
// tripping the testing package's FailNow-from-goroutine rule.
func getClusterLinkConfigSoft(cfg envConfig, name string) (string, error) {
	configURL := fmt.Sprintf("%s/kafka/v3/clusters/%s/links/%s/configs", cfg.RestProxyEndpoint, cfg.DestClusterID, cfg.ClusterLinkName)
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	args := []string{
		"--context", cfg.KubeContext,
		"-n", cfg.Namespace,
		"exec", cfg.KCPPod, "--",
		"wget", "-qO-", configURL,
	}
	out, err := exec.CommandContext(ctx, "kubectl", args...).CombinedOutput()
	if err != nil {
		return "", fmt.Errorf("wget cluster link configs: %s: %w", out, err)
	}

	var resp struct {
		Data []struct {
			Name  string `json:"name"`
			Value string `json:"value"`
		} `json:"data"`
	}
	if err := json.Unmarshal(out, &resp); err != nil {
		return "", fmt.Errorf("unmarshalling configs response: %s: %w", out, err)
	}
	for _, c := range resp.Data {
		if c.Name == name {
			return c.Value, nil
		}
	}
	return "", nil
}

func readCutoverState(t *testing.T, cfg envConfig, podPath string) cutoverState {
	t.Helper()

	data := readPodFile(t, cfg, podPath)

	var state cutoverState
	require.NoError(t, json.Unmarshal(data, &state))

	return state
}

// mirrorTopicStatus is a single entry from the cluster link's mirrors listing.
type mirrorTopicStatus struct {
	Name   string
	Status string
}

// listMirrorTopics fetches the cluster link's mirror topics and their statuses
// via the destination Kafka REST proxy (reachable from inside the pod). Mirrors
// the endpoint kcp itself polls, so it observes the same ACTIVE/PENDING_STOPPED/
// STOPPED transitions.
func listMirrorTopics(cfg envConfig) ([]mirrorTopicStatus, error) {
	mirrorsURL := fmt.Sprintf("%s/kafka/v3/clusters/%s/links/%s/mirrors", cfg.RestProxyEndpoint, cfg.DestClusterID, cfg.ClusterLinkName)
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	args := []string{
		"--context", cfg.KubeContext,
		"-n", cfg.Namespace,
		"exec", cfg.KCPPod, "--",
		"wget", "-qO-", mirrorsURL,
	}
	out, err := exec.CommandContext(ctx, "kubectl", args...).CombinedOutput()
	if err != nil {
		return nil, fmt.Errorf("wget cluster link mirrors: %s: %w", out, err)
	}

	var resp struct {
		Data []struct {
			MirrorTopicName string `json:"mirror_topic_name"`
			MirrorStatus    string `json:"mirror_status"`
		} `json:"data"`
	}
	if err := json.Unmarshal(out, &resp); err != nil {
		return nil, fmt.Errorf("unmarshalling mirrors response: %s: %w", out, err)
	}

	result := make([]mirrorTopicStatus, 0, len(resp.Data))
	for _, d := range resp.Data {
		result = append(result, mirrorTopicStatus{Name: d.MirrorTopicName, Status: d.MirrorStatus})
	}
	return result, nil
}

// assertAllMirrorsStopped verifies that every expected topic's mirror reports
// the terminal STOPPED status. Polls briefly to absorb any REST eventual
// consistency (kcp gates on STOPPED, so this should already be true).
func assertAllMirrorsStopped(t *testing.T, cfg envConfig, expectedTopics []string) {
	t.Helper()

	deadline := time.Now().Add(30 * time.Second)
	var statusByName map[string]string
	for {
		mirrors, err := listMirrorTopics(cfg)
		require.NoError(t, err, "failed to list mirror topics")

		statusByName = make(map[string]string, len(mirrors))
		for _, m := range mirrors {
			statusByName[m.Name] = m.Status
		}

		allStopped := true
		for _, topic := range expectedTopics {
			if statusByName[topic] != "STOPPED" {
				allStopped = false
				break
			}
		}
		if allStopped || time.Now().After(deadline) {
			break
		}
		time.Sleep(2 * time.Second)
	}

	for _, topic := range expectedTopics {
		assert.Equal(t, "STOPPED", statusByName[topic],
			"mirror topic %q should be STOPPED after promotion (statuses: %v)", topic, statusByName)
	}
}

// podFileLineCount returns the number of lines in a file inside the runner pod,
// or 0 if the file does not exist. Used to snapshot kcp.log before an action so
// only the newly-appended lines are inspected afterward.
func podFileLineCount(t *testing.T, cfg envConfig, podPath string) int {
	t.Helper()
	out, err := runInPod(t, cfg, 30*time.Second, "sh", "-c",
		fmt.Sprintf("wc -l < %s 2>/dev/null || echo 0", podPath))
	if err != nil {
		return 0
	}
	n, _ := strconv.Atoi(strings.TrimSpace(out))
	return n
}

// readPodFileLinesFrom reads a file from the runner pod and returns the lines
// starting at startLine (0-indexed), i.e. the lines appended since a snapshot
// taken with podFileLineCount.
func readPodFileLinesFrom(t *testing.T, cfg envConfig, podPath string, startLine int) []string {
	t.Helper()
	data := readPodFile(t, cfg, podPath)
	lines := strings.Split(string(data), "\n")
	if startLine >= len(lines) {
		return nil
	}
	return lines[startLine:]
}

// Constants used by the producer/consumer subtests. Topic name comes from
// the scenario-resolved cfg.TopicName.
const (
	e2eProducerLog    = "producer"
	e2eConsumerGroup  = "kcp-e2e-consumer-group"
	e2eProducerBinary = "/workspace/producer"
	e2eConsumerBinary = "/workspace/consumer"
)

// startConsumerOnSource runs the consumer binary inside the pod to drain a
// few messages from the source cluster and commit offsets. Blocks until the
// consumer exits.
func startConsumerOnSource(t *testing.T, cfg envConfig, maxMessages int) {
	t.Helper()
	out, err := runInPod(t, cfg, 2*time.Minute,
		e2eConsumerBinary,
		"--bootstrap", cfg.SourceBootstrap,
		"--topic", cfg.TopicName,
		"--group", e2eConsumerGroup,
		"--max-messages", fmt.Sprintf("%d", maxMessages),
		"--timeout", "90s",
	)
	require.NoError(t, err, "consumer run failed:\n%s", out)
	t.Logf("consumer output:\n%s", out)
}

// startProducerOnSource starts the producer in the background. Caller must
// invoke stopProducer to terminate it.
func startProducerOnSource(t *testing.T, cfg envConfig, duration time.Duration) {
	t.Helper()
	runInPodBackground(t, cfg, e2eProducerLog,
		e2eProducerBinary,
		"--bootstrap", cfg.SourceBootstrap,
		"--topic", cfg.TopicName,
		"--duration", duration.String(),
		"--rate", "10",
	)
}

func stopProducer(t *testing.T, cfg envConfig) {
	t.Helper()
	killInPod(t, cfg, e2eProducerBinary)
}

func TestCutoverE2E(t *testing.T) {
	cfg := loadEnvConfig(t, scenarioBaseline)

	// Set up K8s clients for assertions (runs on host, uses host kubeconfig)
	kubeConfig, err := clientcmd.NewNonInteractiveDeferredLoadingClientConfig(
		&clientcmd.ClientConfigLoadingRules{ExplicitPath: cfg.Kubeconfig},
		&clientcmd.ConfigOverrides{CurrentContext: cfg.KubeContext},
	).ClientConfig()
	require.NoError(t, err, "failed to build kubeconfig")

	dynClient, err := dynamic.NewForConfig(kubeConfig)
	require.NoError(t, err)

	clientset, err := kubernetes.NewForConfig(kubeConfig)
	require.NoError(t, err)

	// State file lives inside the runner pod
	stateFile := "/workspace/cutover-state.json"

	// Record Gateway pod UIDs before cutover
	podUIDsBefore := getGatewayPodUIDs(t, clientset, cfg.Namespace, cfg.GatewayName)
	t.Logf("Gateway pods before cutover: %d pods", len(podUIDsBefore))

	// --- Step 0: prime source with baseline producer + consumer offsets ---
	// The consumer commits offsets on the source pre-cutover. With the
	// default cutover flow (no --pause-consumer-offset-sync flag), the
	// cluster link will mirror these committed offsets to the destination.
	t.Run("seed_baseline_producer", func(t *testing.T) {
		// 10 quick records to give the consumer something to commit on.
		startProducerOnSource(t, cfg, 10*time.Second)
		// Let the producer get ahead of the consumer.
		time.Sleep(2 * time.Second)
	})

	t.Run("baseline_consumer_commits_offsets", func(t *testing.T) {
		startConsumerOnSource(t, cfg, 20)
	})

	t.Run("stop_baseline_producer", func(t *testing.T) {
		stopProducer(t, cfg)
	})

	// --- Step 1: kcp cutover init ---
	t.Run("init", func(t *testing.T) {
		initArgs := []string{
			"cutover", "init",
			"--source-bootstrap", cfg.SourceBootstrap,
			"--cluster-bootstrap", cfg.DestBootstrap,
			"--cluster-id", cfg.DestClusterID,
			"--cluster-rest-endpoint", cfg.RestProxyEndpoint,
			"--cluster-link-name", cfg.ClusterLinkName,
			"--cluster-api-key", cfg.ClusterAPIKey,
			"--cluster-api-secret", cfg.ClusterAPISecret,
			"--k8s-namespace", cfg.Namespace,
			"--initial-cr-name", cfg.GatewayName,
			"--fenced-cr-yaml", cfg.FencedCR,
			"--switchover-cr-yaml", cfg.SwitchoverCR,
			"--cutover-state-file", stateFile,
			"--use-unauthenticated-plaintext",
			"--kube-path", cfg.KubePath,
			"--insecure-skip-tls-verify",
		}

		stdout, stderr, err := runKCP(t, cfg, initArgs...)
		t.Logf("init stdout:\n%s", stdout)
		t.Logf("init stderr:\n%s", stderr)
		require.NoError(t, err, "kcp cutover init failed")

		// Assert: state file exists with initialized state
		state := readCutoverState(t, cfg, stateFile)
		require.Len(t, state.Cutovers, 1, "expected exactly 1 cutover")
		assert.Equal(t, "initialized", state.Cutovers[0].CurrentState)
		t.Logf("Cutover ID: %s", state.Cutovers[0].CutoverID)
	})

	if t.Failed() {
		t.FailNow()
	}

	// --- Step 2: producer keeps writing during execute ---
	t.Run("start_producer_during_execute", func(t *testing.T) {
		startProducerOnSource(t, cfg, 5*time.Minute)
		// Give producer a moment to push records before kcp inspects lags.
		time.Sleep(2 * time.Second)
	})

	t.Cleanup(func() { stopProducer(t, cfg) })

	// --- Step 3: kcp cutover execute ---
	t.Run("execute", func(t *testing.T) {
		// Get cutover ID from state file
		state := readCutoverState(t, cfg, stateFile)
		require.Len(t, state.Cutovers, 1)
		cutoverID := state.Cutovers[0].CutoverID

		executeArgs := []string{
			"cutover", "execute",
			"--cutover-id", cutoverID,
			"--cutover-state-file", stateFile,
			"--cluster-api-key", cfg.ClusterAPIKey,
			"--cluster-api-secret", cfg.ClusterAPISecret,
			"--lag-threshold", "0",
			"--use-unauthenticated-plaintext",
			"--insecure-skip-tls-verify",
		}

		stdout, stderr, err := runKCP(t, cfg, executeArgs...)
		t.Logf("execute stdout:\n%s", stdout)
		t.Logf("execute stderr:\n%s", stderr)
		require.NoError(t, err, "kcp cutover execute failed")

		// Assert: state file shows switched
		state = readCutoverState(t, cfg, stateFile)
		require.Len(t, state.Cutovers, 1)
		assert.Equal(t, "switched", state.Cutovers[0].CurrentState)
	})

	if t.Failed() {
		t.FailNow()
	}

	// --- Step 2b: Verify mirror topics actually reached STOPPED ---
	// The migration only reports success once kcp confirms each promoted mirror
	// topic transitioned to the terminal STOPPED state (not merely that the
	// promote request was accepted). Assert that end state directly.
	t.Run("verify_mirror_topics_stopped", func(t *testing.T) {
		assertAllMirrorsStopped(t, cfg, cfg.TopicNames)
	})

	// --- Step 3: Verify Gateway CR matches switchover fixture ---
	t.Run("verify_gateway_cr", func(t *testing.T) {
		cr := getGatewayCR(t, dynClient, cfg.Namespace, cfg.GatewayName)

		// Extract spec.routes[0] for targeted field comparison
		spec, found, err := unstructured.NestedMap(cr.Object, "spec")
		require.NoError(t, err)
		require.True(t, found, "spec not found in Gateway CR")

		// Verify no fence config (switchover removes the fence)
		routes, found, err := unstructured.NestedSlice(spec, "routes")
		require.NoError(t, err)
		require.True(t, found, "routes not found in spec")
		require.Len(t, routes, 1)

		route, ok := routes[0].(map[string]interface{})
		require.True(t, ok, "expected route to be a map")
		_, hasFence := route["fence"]
		assert.False(t, hasFence, "switchover CR should not have fence config")

		// Verify streaming domain points to destination
		streamingDomains, found, err := unstructured.NestedSlice(spec, "streamingDomains")
		require.NoError(t, err)
		require.True(t, found)
		require.Len(t, streamingDomains, 1)

		domain, ok := streamingDomains[0].(map[string]interface{})
		require.True(t, ok, "expected streaming domain to be a map")
		domainName, _, _ := unstructured.NestedString(domain, "name")
		assert.Equal(t, "destination-kafka-cluster", domainName, "switchover should point to destination streaming domain")
	})

	if t.Failed() {
		t.FailNow()
	}

	// --- Step 4: Verify Gateway pods rolled out ---
	t.Run("verify_pod_rollout", func(t *testing.T) {
		podUIDsAfter := getGatewayPodUIDs(t, clientset, cfg.Namespace, cfg.GatewayName)
		t.Logf("Gateway pods after cutover: %d pods", len(podUIDsAfter))

		// At least one pod UID should have changed (rollout occurred)
		allSame := true
		for uid := range podUIDsAfter {
			if _, existed := podUIDsBefore[uid]; !existed {
				allSame = false
				break
			}
		}
		assert.False(t, allSame, "expected Gateway pods to have rolled out (new UIDs)")
	})

	// --- Step 5: Regression for R18 — without the flag, kcp must not have
	// touched the cluster link's consumer.offset.sync.enable config.
	t.Run("offset_sync_unchanged", func(t *testing.T) {
		value := getClusterLinkOffsetSyncEnable(t, cfg)
		assert.Equal(t, "true", value, "without --pause-consumer-offset-sync, the cluster link config must remain true throughout the cutover")
	})
}

// TestCutoverE2E_PromoteBatchSize exercises --promote-batch-size against a
// scenario whose cluster link mirrors many topics. With a batch size of 1, kcp
// must promote one topic at a time, waiting for each to reach STOPPED before
// promoting the next — i.e. fully synchronous batches. Asserts:
//   - the cutover reaches switched,
//   - every mirror topic reaches STOPPED,
//   - kcp.log shows one single-topic promote call per topic (no bulk promote),
//     and one STOPPED confirmation per topic.
//
// Runs against the dedicated "batch" scenario provisioned by setup.sh.
func TestCutoverE2E_PromoteBatchSize(t *testing.T) {
	cfg := loadEnvConfig(t, scenarioBatch)
	require.GreaterOrEqual(t, len(cfg.TopicNames), 2,
		"batch scenario must provision multiple topics (got %v)", cfg.TopicNames)

	stateFile := "/workspace/cutover-state-batch.json"
	const logPath = "/workspace/kcp.log"

	// --- Step 1: init ---
	t.Run("init", func(t *testing.T) {
		initArgs := []string{
			"cutover", "init",
			"--source-bootstrap", cfg.SourceBootstrap,
			"--cluster-bootstrap", cfg.DestBootstrap,
			"--cluster-id", cfg.DestClusterID,
			"--cluster-rest-endpoint", cfg.RestProxyEndpoint,
			"--cluster-link-name", cfg.ClusterLinkName,
			"--cluster-api-key", cfg.ClusterAPIKey,
			"--cluster-api-secret", cfg.ClusterAPISecret,
			"--k8s-namespace", cfg.Namespace,
			"--initial-cr-name", cfg.GatewayName,
			"--fenced-cr-yaml", cfg.FencedCR,
			"--switchover-cr-yaml", cfg.SwitchoverCR,
			"--cutover-state-file", stateFile,
			"--use-unauthenticated-plaintext",
			"--kube-path", cfg.KubePath,
			"--insecure-skip-tls-verify",
		}

		stdout, stderr, err := runKCP(t, cfg, initArgs...)
		t.Logf("init stdout:\n%s", stdout)
		t.Logf("init stderr:\n%s", stderr)
		require.NoError(t, err, "kcp cutover init failed")

		state := readCutoverState(t, cfg, stateFile)
		require.Len(t, state.Cutovers, 1)
		assert.Equal(t, "initialized", state.Cutovers[0].CurrentState)
	})

	if t.Failed() {
		t.FailNow()
	}

	// Snapshot kcp.log so the batching assertion only inspects the execute run.
	logStart := podFileLineCount(t, cfg, logPath)

	// --- Step 2: execute with --promote-batch-size 1 ---
	t.Run("execute_batched", func(t *testing.T) {
		state := readCutoverState(t, cfg, stateFile)
		require.Len(t, state.Cutovers, 1)
		cutoverID := state.Cutovers[0].CutoverID

		executeArgs := []string{
			"cutover", "execute",
			"--cutover-id", cutoverID,
			"--cutover-state-file", stateFile,
			"--cluster-api-key", cfg.ClusterAPIKey,
			"--cluster-api-secret", cfg.ClusterAPISecret,
			"--lag-threshold", "0",
			"--promote-batch-size", "1",
			"--use-unauthenticated-plaintext",
			"--insecure-skip-tls-verify",
		}

		stdout, stderr, err := runKCP(t, cfg, executeArgs...)
		t.Logf("execute stdout:\n%s", stdout)
		t.Logf("execute stderr:\n%s", stderr)
		require.NoError(t, err, "kcp cutover execute failed")

		state = readCutoverState(t, cfg, stateFile)
		require.Len(t, state.Cutovers, 1)
		assert.Equal(t, "switched", state.Cutovers[0].CurrentState)
	})

	if t.Failed() {
		t.FailNow()
	}

	// --- Step 3: every mirror topic reached STOPPED ---
	t.Run("all_mirrors_stopped", func(t *testing.T) {
		assertAllMirrorsStopped(t, cfg, cfg.TopicNames)
	})

	// --- Step 4: promotion ran as sequential single-topic batches ---
	t.Run("promoted_in_single_topic_batches", func(t *testing.T) {
		lines := readPodFileLinesFrom(t, cfg, logPath, logStart)
		require.NotEmpty(t, lines, "expected new kcp.log lines from the execute run")

		var singleTopicPromotes, bulkPromotes, stoppedConfirms int
		for _, ln := range lines {
			if strings.Contains(ln, "promoting mirror topics") {
				if strings.Contains(ln, "topicCount=1 topics=") {
					singleTopicPromotes++
				} else {
					bulkPromotes++
				}
			}
			if strings.Contains(ln, "mirror topic promotion confirmed stopped") {
				stoppedConfirms++
			}
		}

		n := len(cfg.TopicNames)
		assert.Equal(t, n, singleTopicPromotes,
			"expected exactly one single-topic promote call per topic with --promote-batch-size 1")
		assert.Zero(t, bulkPromotes,
			"no promote call should contain more than one topic with --promote-batch-size 1")
		assert.Equal(t, n, stoppedConfirms,
			"each promoted topic should be individually confirmed STOPPED")
	})
}

// TestCutoverE2E_PauseOffsetSync_HappyPath exercises the full
// --pause-consumer-offset-sync flow: init records intent, execute disables
// the config before the FSM, runs the cutover, then restores the config
// after switchover. Asserts the true → false → true transition is
// observable via ListConfigs polling.
//
// Runs against the "pause-sync-happy" scenario — its own dedicated source
// topic, cluster link, and gateway CR provisioned by setup.sh — so it is
// independent of TestCutoverE2E.
func TestCutoverE2E_PauseOffsetSync_HappyPath(t *testing.T) {
	cfg := loadEnvConfig(t, scenarioPauseSyncHappy)

	stateFile := "/workspace/cutover-state-pause-sync-happy.json"

	// Make sure no leftover producer is running from a prior test.
	stopProducer(t, cfg)

	// Sanity check: cluster link starts with enable=true.
	startValue := getClusterLinkOffsetSyncEnable(t, cfg)
	require.Equal(t, "true", startValue, "fixture must start with consumer.offset.sync.enable=true")

	// Pre-existing consumer commits on the source so we have a non-zero
	// committed offset that would, in the default flow, be mirrored to dest.
	t.Run("seed_baseline", func(t *testing.T) {
		startProducerOnSource(t, cfg, 10*time.Second)
		time.Sleep(2 * time.Second)
		startConsumerOnSource(t, cfg, 20)
		stopProducer(t, cfg)
	})

	// --- Step 1: init with the flag ---
	t.Run("init_with_flag", func(t *testing.T) {
		initArgs := []string{
			"cutover", "init",
			"--source-bootstrap", cfg.SourceBootstrap,
			"--cluster-bootstrap", cfg.DestBootstrap,
			"--cluster-id", cfg.DestClusterID,
			"--cluster-rest-endpoint", cfg.RestProxyEndpoint,
			"--cluster-link-name", cfg.ClusterLinkName,
			"--cluster-api-key", cfg.ClusterAPIKey,
			"--cluster-api-secret", cfg.ClusterAPISecret,
			"--k8s-namespace", cfg.Namespace,
			"--initial-cr-name", cfg.GatewayName,
			"--fenced-cr-yaml", cfg.FencedCR,
			"--switchover-cr-yaml", cfg.SwitchoverCR,
			"--cutover-state-file", stateFile,
			"--use-unauthenticated-plaintext",
			"--kube-path", cfg.KubePath,
			"--insecure-skip-tls-verify",
			"--pause-consumer-offset-sync",
		}

		stdout, stderr, err := runKCP(t, cfg, initArgs...)
		t.Logf("init stdout:\n%s", stdout)
		t.Logf("init stderr:\n%s", stderr)
		require.NoError(t, err, "kcp cutover init failed")

		state := readCutoverState(t, cfg, stateFile)
		require.Len(t, state.Cutovers, 1)
		assert.True(t, state.Cutovers[0].PauseConsumerOffsetSync, "intent must persist")
		assert.False(t, state.Cutovers[0].PauseConsumerOffsetSyncFlipped, "marker must NOT be flipped at init time")
	})

	// After init the config should STILL be true — init only records intent.
	t.Run("config_still_true_after_init", func(t *testing.T) {
		assert.Equal(t, "true", getClusterLinkOffsetSyncEnable(t, cfg))
	})

	// --- Step 2: producer running during execute ---
	t.Run("start_producer", func(t *testing.T) {
		startProducerOnSource(t, cfg, 5*time.Minute)
		time.Sleep(2 * time.Second)
	})
	t.Cleanup(func() { stopProducer(t, cfg) })

	// Best-effort polling of the live cluster-link config alongside execute.
	// This is purely advisory: it produces a log line showing the observed
	// true→false→true sequence when timing permits, but a fast FSM run may
	// not catch the disabled window. The deterministic check is on the
	// bookend's stdout lines (asserted below). The goroutine uses the Soft
	// variant because require.NoError on the parent *testing.T is unsafe
	// from a non-test goroutine — transient wget/JSON errors are swallowed
	// locally instead of crashing the test.
	configObservations := make(chan string, 100)
	pollCtx, cancelPoll := context.WithCancel(context.Background())
	pollDone := make(chan struct{})
	go func() {
		defer close(pollDone)
		ticker := time.NewTicker(200 * time.Millisecond)
		defer ticker.Stop()
		for {
			select {
			case <-pollCtx.Done():
				return
			case <-ticker.C:
				v, err := getClusterLinkOffsetSyncEnableSoft(cfg)
				if err != nil {
					continue
				}
				select {
				case configObservations <- v:
				default:
				}
			}
		}
	}()

	var executeStdout string
	t.Run("execute_with_flag", func(t *testing.T) {
		state := readCutoverState(t, cfg, stateFile)
		require.Len(t, state.Cutovers, 1)
		cutoverID := state.Cutovers[0].CutoverID

		executeArgs := []string{
			"cutover", "execute",
			"--cutover-id", cutoverID,
			"--cutover-state-file", stateFile,
			"--cluster-api-key", cfg.ClusterAPIKey,
			"--cluster-api-secret", cfg.ClusterAPISecret,
			"--lag-threshold", "0",
			"--use-unauthenticated-plaintext",
			"--insecure-skip-tls-verify",
		}

		stdout, stderr, err := runKCP(t, cfg, executeArgs...)
		executeStdout = stdout
		t.Logf("execute stdout:\n%s", stdout)
		t.Logf("execute stderr:\n%s", stderr)
		require.NoError(t, err, "kcp cutover execute failed")

		state = readCutoverState(t, cfg, stateFile)
		require.Len(t, state.Cutovers, 1)
		assert.Equal(t, "switched", state.Cutovers[0].CurrentState)
		assert.False(t, state.Cutovers[0].PauseConsumerOffsetSyncFlipped, "marker must clear after successful restore")
	})

	cancelPoll()
	<-pollDone

	// Log the observed sequence (advisory only — see comment on the poller).
	close(configObservations)
	seen := []string{}
	for v := range configObservations {
		if len(seen) == 0 || seen[len(seen)-1] != v {
			seen = append(seen, v)
		}
	}
	t.Logf("observed cluster-link config sequence during execute (advisory): %v", seen)

	// --- Step 3: deterministic assertions ---
	t.Run("bookend_ran_and_final_state_restored", func(t *testing.T) {
		// The bookend prints these lines unconditionally when it runs. They
		// are durable evidence that the disable→restore cycle executed,
		// without depending on poll timing landing inside the FSM window.
		assert.Contains(t, executeStdout, "Pausing consumer.offset.sync",
			"execute stdout must show the disable bookend ran")
		assert.Contains(t, executeStdout, "Restoring consumer.offset.sync",
			"execute stdout must show the restore bookend ran")

		// And the live cluster link must be back to enable=true.
		assert.Equal(t, "true", getClusterLinkOffsetSyncEnable(t, cfg),
			"final state must be restored to true")
	})
}

// TestCutoverE2E_PauseOffsetSync_InitRefuses verifies that when the
// cluster link's consumer.offset.sync.enable is NOT "true", init with the
// flag exits non-zero with a useful message.
//
// Runs against the "pause-sync-refuses" scenario, which gives this test
// its own cluster link so flipping offset-sync to "false" does not leak
// into other tests.
func TestCutoverE2E_PauseOffsetSync_InitRefuses(t *testing.T) {
	cfg := loadEnvConfig(t, scenarioPauseSyncRefuses)

	setClusterLinkConfig(t, cfg, "consumer.offset.sync.enable", "false")
	t.Cleanup(func() {
		setClusterLinkConfig(t, cfg, "consumer.offset.sync.enable", "true")
	})

	// Best-effort wait for the config to propagate.
	for i := 0; i < 10; i++ {
		if getClusterLinkOffsetSyncEnable(t, cfg) == "false" {
			break
		}
		time.Sleep(500 * time.Millisecond)
	}
	require.Equal(t, "false", getClusterLinkOffsetSyncEnable(t, cfg), "fixture must be flipped to false before this test runs")

	stateFile := "/workspace/cutover-state-refuse.json"

	initArgs := []string{
		"cutover", "init",
		"--source-bootstrap", cfg.SourceBootstrap,
		"--cluster-bootstrap", cfg.DestBootstrap,
		"--cluster-id", cfg.DestClusterID,
		"--cluster-rest-endpoint", cfg.RestProxyEndpoint,
		"--cluster-link-name", cfg.ClusterLinkName,
		"--cluster-api-key", cfg.ClusterAPIKey,
		"--cluster-api-secret", cfg.ClusterAPISecret,
		"--k8s-namespace", cfg.Namespace,
		"--initial-cr-name", cfg.GatewayName,
		"--fenced-cr-yaml", cfg.FencedCR,
		"--switchover-cr-yaml", cfg.SwitchoverCR,
		"--cutover-state-file", stateFile,
		"--use-unauthenticated-plaintext",
		"--kube-path", cfg.KubePath,
		"--insecure-skip-tls-verify",
		"--pause-consumer-offset-sync",
	}

	stdout, stderr, err := runKCP(t, cfg, initArgs...)
	t.Logf("init stdout:\n%s", stdout)
	t.Logf("init stderr:\n%s", stderr)
	require.Error(t, err, "init must fail when cluster link offset sync is not true")
	combined := stdout + stderr
	assert.Contains(t, combined, cfg.ClusterLinkName, "error must name the cluster link")
	assert.Contains(t, combined, "consumer.offset.sync.enable", "error must name the config key")
}

// TestCutoverE2E_PauseOffsetSync_RestoresFilters verifies that a
// consumer.offset.group.filters value configured on the cluster link before
// init is preserved across the --pause-consumer-offset-sync round-trip.
//
// The bookend exists because setting consumer.offset.sync.enable=false on a
// cluster link clears consumer.offset.group.filters as a side effect on both
// Confluent Cloud and Confluent Platform. The disable bookend triggers that
// clearing; the restore bookend re-applies filters from the init-time
// snapshot. This test exercises that round-trip end-to-end.
//
// Runs against the "pause-sync-restores-filters" scenario — its own
// dedicated source topic, cluster link, and gateway CR provisioned by
// setup.sh — so it is independent of the other cutover tests.
func TestCutoverE2E_PauseOffsetSync_RestoresFilters(t *testing.T) {
	cfg := loadEnvConfig(t, scenarioPauseSyncRestoresFilters)

	stateFile := "/workspace/cutover-state-pause-sync-restores-filters.json"
	stopProducer(t, cfg)

	const filtersKey = "consumer.offset.group.filters"
	const filtersValue = `{"groupFilters":[{"name":"e2e-*","patternType":"PREFIXED","filterType":"INCLUDE"}]}`

	// Pre-populate filters on the cluster link before init so the snapshot
	// captures the value. setClusterLinkConfig fails the test if the CP REST
	// API rejects the PUT (e.g. malformed JSON or unsupported key on this CP
	// version) — a clear signal that the fixture or CP version needs
	// adjustment.
	setClusterLinkConfig(t, cfg, filtersKey, filtersValue)

	// Sanity checks: fixture matches expectations before init runs.
	require.Equal(t, "true", getClusterLinkOffsetSyncEnable(t, cfg), "fixture must start with consumer.offset.sync.enable=true")
	require.Equal(t, filtersValue, getClusterLinkConfig(t, cfg, filtersKey), "fixture must have filters set before init")

	// --- Step 1: init with the flag ---
	t.Run("init_captures_filters_snapshot", func(t *testing.T) {
		initArgs := []string{
			"cutover", "init",
			"--source-bootstrap", cfg.SourceBootstrap,
			"--cluster-bootstrap", cfg.DestBootstrap,
			"--cluster-id", cfg.DestClusterID,
			"--cluster-rest-endpoint", cfg.RestProxyEndpoint,
			"--cluster-link-name", cfg.ClusterLinkName,
			"--cluster-api-key", cfg.ClusterAPIKey,
			"--cluster-api-secret", cfg.ClusterAPISecret,
			"--k8s-namespace", cfg.Namespace,
			"--initial-cr-name", cfg.GatewayName,
			"--fenced-cr-yaml", cfg.FencedCR,
			"--switchover-cr-yaml", cfg.SwitchoverCR,
			"--cutover-state-file", stateFile,
			"--use-unauthenticated-plaintext",
			"--kube-path", cfg.KubePath,
			"--insecure-skip-tls-verify",
			"--pause-consumer-offset-sync",
		}

		stdout, stderr, err := runKCP(t, cfg, initArgs...)
		t.Logf("init stdout:\n%s", stdout)
		t.Logf("init stderr:\n%s", stderr)
		require.NoError(t, err, "kcp cutover init failed")

		state := readCutoverState(t, cfg, stateFile)
		require.Len(t, state.Cutovers, 1)
		assert.True(t, state.Cutovers[0].PauseConsumerOffsetSync, "intent must persist")
		assert.False(t, state.Cutovers[0].PauseConsumerOffsetSyncFlipped, "marker must NOT be flipped at init time")
		assert.Equal(t, filtersValue, state.Cutovers[0].ClusterLinkConfigs[filtersKey],
			"init must capture filters value in the ClusterLinkConfigs snapshot — restore reads from this")
	})

	// --- Step 2: producer running during execute ---
	t.Run("start_producer", func(t *testing.T) {
		startProducerOnSource(t, cfg, 5*time.Minute)
		time.Sleep(2 * time.Second)
	})
	t.Cleanup(func() { stopProducer(t, cfg) })

	// --- Step 3: execute ---
	t.Run("execute_with_flag", func(t *testing.T) {
		state := readCutoverState(t, cfg, stateFile)
		require.Len(t, state.Cutovers, 1)
		cutoverID := state.Cutovers[0].CutoverID

		executeArgs := []string{
			"cutover", "execute",
			"--cutover-id", cutoverID,
			"--cutover-state-file", stateFile,
			"--cluster-api-key", cfg.ClusterAPIKey,
			"--cluster-api-secret", cfg.ClusterAPISecret,
			"--lag-threshold", "0",
			"--use-unauthenticated-plaintext",
			"--insecure-skip-tls-verify",
		}

		stdout, stderr, err := runKCP(t, cfg, executeArgs...)
		t.Logf("execute stdout:\n%s", stdout)
		t.Logf("execute stderr:\n%s", stderr)
		require.NoError(t, err, "kcp cutover execute failed")

		state = readCutoverState(t, cfg, stateFile)
		require.Len(t, state.Cutovers, 1)
		assert.Equal(t, "switched", state.Cutovers[0].CurrentState)
		assert.False(t, state.Cutovers[0].PauseConsumerOffsetSyncFlipped, "marker must clear after successful restore")
	})

	// --- Step 4: post-cutover parity ---
	t.Run("filters_match_init_snapshot", func(t *testing.T) {
		assert.Equal(t, "true", getClusterLinkOffsetSyncEnable(t, cfg), "toggle must be restored to true")
		assert.Equal(t, filtersValue, getClusterLinkConfig(t, cfg, filtersKey),
			"%s must match the value set before init — this is the restore bookend's primary contract", filtersKey)
	})
}
