package report

import (
	"github.com/confluentinc/kcp/cmd/report/costs"
	"github.com/confluentinc/kcp/cmd/report/metrics"
	"github.com/spf13/cobra"
)

func NewReportCmd() *cobra.Command {
	reportCmd := &cobra.Command{
		Use:           "report",
		Short:         "Generate reports of costs and metrics",
		Long:          "Generate reports of region costs and cluster metrics from the statefile generated by `kcp discover`",
		SilenceErrors: true,
		Args:          cobra.NoArgs,
	}

	reportCmd.AddCommand(costs.NewReportCostsCmd())
	reportCmd.AddCommand(metrics.NewReportMetricsCmd())

	return reportCmd
}
