version: 2

project_name: kcp

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    binary: kcp
    ldflags:
      - -s -w 
      - -X github.com/confluentinc/kcp/internal/buildinfo.Version={{.Version}}
      - -X github.com/confluentinc/kcp/internal/buildinfo.Commit={{.Commit}}
      - -X github.com/confluentinc/kcp/internal/buildinfo.Date={{.Date}}

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .Binary }}_ {{- title .Os | tolower }}_ {{- if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }} {{- if .Arm }}v{{ .Arm }}{{ end }}
    wrap_in_directory: '{{ .ProjectName }}'

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
