clusters:
  - id: osk-kafka
    bootstrap_servers:
      - localhost:9092
    auth_method:
      unauthenticated_plaintext:
        use: true
    prometheus:
      url: http://localhost:9290
    metadata:
      environment: test
      location: osk-scan
