clusters:
  - id: osk-kafka
    bootstrap_servers:
      - localhost:9092
    auth_method:
      unauthenticated_plaintext:
        use: true
    prometheus:
      url: https://localhost:9292
      auth:
        username: promuser
        password: prompass
      tls:
        insecure_skip_verify: true
    metadata:
      environment: test
      location: osk-scan
