name: Feature Request
description: Suggest a new feature or enhancement for KCP CLI
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your use case and requirements.

  - type: dropdown
    id: feature-category
    attributes:
      label: Feature Category
      description: Which area of KCP CLI would this feature enhance?
      options:
        - Scanning (kcp scan)
        - Reporting (kcp report)
        - Asset Creation (kcp create-asset)
        - Authentication & Security
        - CLI User Experience
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What pain point are you experiencing?
      placeholder: Describe the current limitation or challenge you're facing...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented
      placeholder: A clear and concise description of what you want to happen...
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case & User Story
      description: Provide a specific use case or user story that demonstrates the value of this feature
      placeholder: |
        As a [type of user], I want [feature] so that [benefit/outcome]...

        Example scenario:
        1. User is trying to...
        2. Currently they have to...
        3. With this feature, they would be able to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: What other approaches could solve this problem?

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What would need to be true for this feature to be considered complete?

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to your workflow?
      options:
        - Low - Nice to have
        - Medium - Would improve my workflow
        - High - Critical for my use case
        - Urgent - Blocking my migration
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, mockups, or examples about the feature request here

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be interested in contributing to this feature?
      options:
        - label: I would be willing to contribute to this feature
          required: false
