//go:build e2e

package migration_test

import (
	"bufio"
	"context"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/client-go/dynamic"
	"k8s.io/client-go/kubernetes"
	"k8s.io/client-go/tools/clientcmd"
)

// envConfig holds connection details loaded from the .env file generated by setup.sh.
type envConfig struct {
	Kubeconfig        string // host kubeconfig for assertions
	KubeContext       string
	Namespace         string
	SourceBootstrap   string
	DestBootstrap     string
	RestProxyEndpoint string
	DestClusterID     string
	ClusterLinkName   string
	ClusterAPIKey     string
	ClusterAPISecret  string
	GatewayName       string
	KCPPod            string // pod running the kcp binary
	KubePath          string // in-pod kubeconfig path
	FencedCR          string // in-pod fixture path
	SwitchoverCR      string // in-pod fixture path
}

func loadEnvConfig(t *testing.T) envConfig {
	t.Helper()

	envFile := filepath.Join(testdataDir(), ".env")
	f, err := os.Open(envFile)
	require.NoError(t, err, "failed to open .env file — did you run 'make test-migration-e2e-setup'?")
	defer f.Close()

	vars := map[string]string{}
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		parts := strings.SplitN(line, "=", 2)
		if len(parts) == 2 {
			vars[parts[0]] = parts[1]
		}
	}
	require.NoError(t, scanner.Err())

	return envConfig{
		Kubeconfig:        vars["KCP_E2E_KUBECONFIG"],
		KubeContext:       vars["KCP_E2E_KUBE_CONTEXT"],
		Namespace:         vars["KCP_E2E_NAMESPACE"],
		SourceBootstrap:   vars["KCP_E2E_SOURCE_BOOTSTRAP"],
		DestBootstrap:     vars["KCP_E2E_DEST_BOOTSTRAP"],
		RestProxyEndpoint: vars["KCP_E2E_REST_PROXY_ENDPOINT"],
		DestClusterID:     vars["KCP_E2E_DEST_CLUSTER_ID"],
		ClusterLinkName:   vars["KCP_E2E_CLUSTER_LINK_NAME"],
		ClusterAPIKey:     vars["KCP_E2E_CLUSTER_API_KEY"],
		ClusterAPISecret:  vars["KCP_E2E_CLUSTER_API_SECRET"],
		GatewayName:       vars["KCP_E2E_GATEWAY_NAME"],
		KCPPod:            vars["KCP_E2E_KCP_POD"],
		KubePath:          vars["KCP_E2E_KUBE_PATH"],
		FencedCR:          vars["KCP_E2E_FENCED_CR"],
		SwitchoverCR:      vars["KCP_E2E_SWITCHOVER_CR"],
	}
}

func testdataDir() string {
	// integration-tests/migration/ -> integration-tests/migration/testdata/
	return filepath.Join("testdata")
}

// runKCP executes the kcp binary inside the runner pod via kubectl exec.
func runKCP(t *testing.T, cfg envConfig, args ...string) (string, string, error) {
	t.Helper()

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Minute)
	defer cancel()

	kubectlArgs := []string{
		"--context", cfg.KubeContext,
		"-n", cfg.Namespace,
		"exec", cfg.KCPPod, "--",
		"/workspace/kcp",
	}
	kubectlArgs = append(kubectlArgs, args...)

	cmd := exec.CommandContext(ctx, "kubectl", kubectlArgs...)
	var stdout, stderr strings.Builder
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr

	err := cmd.Run()
	return stdout.String(), stderr.String(), err
}

// readPodFile reads a file from inside the runner pod.
func readPodFile(t *testing.T, cfg envConfig, podPath string) []byte {
	t.Helper()

	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	cmd := exec.CommandContext(ctx, "kubectl",
		"--context", cfg.KubeContext,
		"-n", cfg.Namespace,
		"exec", cfg.KCPPod, "--",
		"cat", podPath)
	var stderr strings.Builder
	cmd.Stderr = &stderr
	out, err := cmd.Output()
	require.NoError(t, err, "failed to read %s from pod: %s", podPath, stderr.String())
	return out
}

// gatewayGVR is the GroupVersionResource for Confluent Gateway CRs.
var gatewayGVR = schema.GroupVersionResource{
	Group:    "platform.confluent.io",
	Version:  "v1beta1",
	Resource: "gateways",
}

func getGatewayCR(t *testing.T, dynClient dynamic.Interface, namespace, name string) *unstructured.Unstructured {
	t.Helper()

	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	cr, err := dynClient.Resource(gatewayGVR).Namespace(namespace).Get(ctx, name, metav1.GetOptions{})
	require.NoError(t, err, "failed to get Gateway CR %s/%s", namespace, name)

	return cr
}

func getGatewayPodUIDs(t *testing.T, clientset kubernetes.Interface, namespace, gatewayName string) map[string]struct{} {
	t.Helper()

	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	pods, err := clientset.CoreV1().Pods(namespace).List(ctx, metav1.ListOptions{
		LabelSelector: fmt.Sprintf("app=%s", gatewayName),
	})
	require.NoError(t, err)

	uids := make(map[string]struct{}, len(pods.Items))
	for _, pod := range pods.Items {
		uids[string(pod.UID)] = struct{}{}
	}
	return uids
}

// migrationState mirrors the state file structure for assertion purposes.
type migrationState struct {
	Migrations []migrationConfig `json:"migrations"`
}

type migrationConfig struct {
	MigrationID  string `json:"migration_id"`
	CurrentState string `json:"current_state"`
}

func readMigrationState(t *testing.T, cfg envConfig, podPath string) migrationState {
	t.Helper()

	data := readPodFile(t, cfg, podPath)

	var state migrationState
	require.NoError(t, json.Unmarshal(data, &state))

	return state
}

func TestMigrationE2E(t *testing.T) {
	cfg := loadEnvConfig(t)

	// Set up K8s clients for assertions (runs on host, uses host kubeconfig)
	kubeConfig, err := clientcmd.NewNonInteractiveDeferredLoadingClientConfig(
		&clientcmd.ClientConfigLoadingRules{ExplicitPath: cfg.Kubeconfig},
		&clientcmd.ConfigOverrides{CurrentContext: cfg.KubeContext},
	).ClientConfig()
	require.NoError(t, err, "failed to build kubeconfig")

	dynClient, err := dynamic.NewForConfig(kubeConfig)
	require.NoError(t, err)

	clientset, err := kubernetes.NewForConfig(kubeConfig)
	require.NoError(t, err)

	// State file lives inside the runner pod
	stateFile := "/workspace/migration-state.json"

	// Record Gateway pod UIDs before migration
	podUIDsBefore := getGatewayPodUIDs(t, clientset, cfg.Namespace, cfg.GatewayName)
	t.Logf("Gateway pods before migration: %d pods", len(podUIDsBefore))

	// --- Step 1: kcp migration init ---
	t.Run("init", func(t *testing.T) {
		initArgs := []string{
			"migration", "init",
			"--source-bootstrap", cfg.SourceBootstrap,
			"--cluster-bootstrap", cfg.DestBootstrap,
			"--cluster-id", cfg.DestClusterID,
			"--cluster-rest-endpoint", cfg.RestProxyEndpoint,
			"--cluster-link-name", cfg.ClusterLinkName,
			"--cluster-api-key", cfg.ClusterAPIKey,
			"--cluster-api-secret", cfg.ClusterAPISecret,
			"--k8s-namespace", cfg.Namespace,
			"--initial-cr-name", cfg.GatewayName,
			"--fenced-cr-yaml", cfg.FencedCR,
			"--switchover-cr-yaml", cfg.SwitchoverCR,
			"--migration-state-file", stateFile,
			"--use-unauthenticated-plaintext",
			"--kube-path", cfg.KubePath,
			"--insecure-skip-tls-verify",
		}

		stdout, stderr, err := runKCP(t, cfg, initArgs...)
		t.Logf("init stdout:\n%s", stdout)
		t.Logf("init stderr:\n%s", stderr)
		require.NoError(t, err, "kcp migration init failed")

		// Assert: state file exists with initialized state
		state := readMigrationState(t, cfg, stateFile)
		require.Len(t, state.Migrations, 1, "expected exactly 1 migration")
		assert.Equal(t, "initialized", state.Migrations[0].CurrentState)
		t.Logf("Migration ID: %s", state.Migrations[0].MigrationID)
	})

	if t.Failed() {
		t.FailNow()
	}

	// --- Step 2: kcp migration execute ---
	t.Run("execute", func(t *testing.T) {
		// Get migration ID from state file
		state := readMigrationState(t, cfg, stateFile)
		require.Len(t, state.Migrations, 1)
		migrationID := state.Migrations[0].MigrationID

		executeArgs := []string{
			"migration", "execute",
			"--migration-id", migrationID,
			"--migration-state-file", stateFile,
			"--cluster-api-key", cfg.ClusterAPIKey,
			"--cluster-api-secret", cfg.ClusterAPISecret,
			"--lag-threshold", "0",
			"--use-unauthenticated-plaintext",
			"--insecure-skip-tls-verify",
		}

		stdout, stderr, err := runKCP(t, cfg, executeArgs...)
		t.Logf("execute stdout:\n%s", stdout)
		t.Logf("execute stderr:\n%s", stderr)
		require.NoError(t, err, "kcp migration execute failed")

		// Assert: state file shows switched
		state = readMigrationState(t, cfg, stateFile)
		require.Len(t, state.Migrations, 1)
		assert.Equal(t, "switched", state.Migrations[0].CurrentState)
	})

	if t.Failed() {
		t.FailNow()
	}

	// --- Step 3: Verify Gateway CR matches switchover fixture ---
	t.Run("verify_gateway_cr", func(t *testing.T) {
		cr := getGatewayCR(t, dynClient, cfg.Namespace, cfg.GatewayName)

		// Extract spec.routes[0] for targeted field comparison
		spec, found, err := unstructured.NestedMap(cr.Object, "spec")
		require.NoError(t, err)
		require.True(t, found, "spec not found in Gateway CR")

		// Verify no fence config (switchover removes the fence)
		routes, found, err := unstructured.NestedSlice(spec, "routes")
		require.NoError(t, err)
		require.True(t, found, "routes not found in spec")
		require.Len(t, routes, 1)

		route, ok := routes[0].(map[string]interface{})
		require.True(t, ok, "expected route to be a map")
		_, hasFence := route["fence"]
		assert.False(t, hasFence, "switchover CR should not have fence config")

		// Verify streaming domain points to destination
		streamingDomains, found, err := unstructured.NestedSlice(spec, "streamingDomains")
		require.NoError(t, err)
		require.True(t, found)
		require.Len(t, streamingDomains, 1)

		domain, ok := streamingDomains[0].(map[string]interface{})
		require.True(t, ok, "expected streaming domain to be a map")
		domainName, _, _ := unstructured.NestedString(domain, "name")
		assert.Equal(t, "destination-kafka-cluster", domainName, "switchover should point to destination streaming domain")
	})

	if t.Failed() {
		t.FailNow()
	}

	// --- Step 4: Verify Gateway pods rolled out ---
	t.Run("verify_pod_rollout", func(t *testing.T) {
		podUIDsAfter := getGatewayPodUIDs(t, clientset, cfg.Namespace, cfg.GatewayName)
		t.Logf("Gateway pods after migration: %d pods", len(podUIDsAfter))

		// At least one pod UID should have changed (rollout occurred)
		allSame := true
		for uid := range podUIDsAfter {
			if _, existed := podUIDsBefore[uid]; !existed {
				allSame = false
				break
			}
		}
		assert.False(t, allSame, "expected Gateway pods to have rolled out (new UIDs)")
	})
}
