//go:build e2e

package migration_test

import (
	"bufio"
	"context"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/client-go/dynamic"
	"k8s.io/client-go/kubernetes"
	"k8s.io/client-go/tools/clientcmd"
)

// Scenario names. Each scenario maps to a dedicated set of resources
// (source topic, cluster link, gateway CR) provisioned by setup.sh so that
// tests are fully isolated and do not depend on execution order.
const (
	scenarioBaseline                   = "baseline"                      // TestMigrationE2E
	scenarioPauseSyncHappy             = "pause-sync-happy"              // TestMigrationE2E_PauseOffsetSync_HappyPath
	scenarioPauseSyncRefuses           = "pause-sync-refuses"            // TestMigrationE2E_PauseOffsetSync_InitRefuses
	scenarioPauseSyncRestoresFilters   = "pause-sync-restores-filters"   // TestMigrationE2E_PauseOffsetSync_RestoresFilters
	scenarioPauseSyncRogue             = "pause-sync-rogue"              // TestMigrationE2E_PauseOffsetSync_RogueProducerRollback
	scenarioPauseSyncDrift             = "pause-sync-drift"              // TestMigrationE2E_PauseOffsetSync_DriftRollsBackFence
	scenarioPauseSyncDrain             = "pause-sync-drain"              // TestMigrationE2E_PauseOffsetSync_Drain
	scenarioBatch                      = "batch"                         // TestMigrationE2E_PromoteBatchSize
	scenarioRogueProducer              = "rogue-producer"                // TestMigrationE2E_RogueProducerDetection
	scenarioRogueProducerFalsePositive = "rogue-producer-false-positive" // TestMigrationE2E_RogueProducerFalsePositive
)

// envConfig holds connection details loaded from the .env file generated by
// setup.sh, resolved for a specific scenario.
type envConfig struct {
	Kubeconfig        string // host kubeconfig for assertions
	KubeContext       string
	Namespace         string
	SourceBootstrap   string
	DestBootstrap     string
	RestProxyEndpoint string
	DestClusterID     string
	ClusterAPIKey     string
	ClusterAPISecret  string
	KCPPod            string // pod running the kcp binary
	KubePath          string // in-pod kubeconfig path

	// Per-scenario resources.
	Scenario        string
	ClusterLinkName string
	TopicName       string   // single-topic scenarios (producer/consumer target)
	TopicNames      []string // all mirror topics for the scenario (>=1)
	GatewayName     string
	FencedCR        string // in-pod fixture path
	SwitchoverCR    string // in-pod fixture path
}

func loadEnvConfig(t *testing.T, scenario string) envConfig {
	t.Helper()

	envFile := filepath.Join(testdataDir(), ".env")
	f, err := os.Open(envFile)
	require.NoError(t, err, "failed to open .env file — did you run 'make test-migration-setup'?")
	defer f.Close()

	vars := map[string]string{}
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		parts := strings.SplitN(line, "=", 2)
		if len(parts) == 2 {
			vars[parts[0]] = parts[1]
		}
	}
	require.NoError(t, scanner.Err())

	// Sanity-check the scenario was provisioned by setup.sh.
	provisioned := strings.Split(vars["KCP_E2E_SCENARIOS"], ",")
	found := false
	for _, s := range provisioned {
		if s == scenario {
			found = true
			break
		}
	}
	require.True(t, found, "scenario %q not provisioned by setup.sh (KCP_E2E_SCENARIOS=%q)", scenario, vars["KCP_E2E_SCENARIOS"])

	// Per-scenario env-var prefix: lowercase-dash -> UPPERCASE_UNDERSCORE.
	prefix := "KCP_E2E_" + strings.ReplaceAll(strings.ToUpper(scenario), "-", "_") + "_"

	// TopicNames comes from the comma-separated <PREFIX>TOPIC_NAMES var when
	// present (multi-topic scenarios); otherwise it falls back to the single
	// TOPIC_NAME so every scenario exposes a non-empty list.
	topicName := vars[prefix+"TOPIC_NAME"]
	var topicNames []string
	if names := vars[prefix+"TOPIC_NAMES"]; names != "" {
		topicNames = strings.Split(names, ",")
	} else if topicName != "" {
		topicNames = []string{topicName}
	}

	return envConfig{
		Kubeconfig:        vars["KCP_E2E_KUBECONFIG"],
		KubeContext:       vars["KCP_E2E_KUBE_CONTEXT"],
		Namespace:         vars["KCP_E2E_NAMESPACE"],
		SourceBootstrap:   vars["KCP_E2E_SOURCE_BOOTSTRAP"],
		DestBootstrap:     vars["KCP_E2E_DEST_BOOTSTRAP"],
		RestProxyEndpoint: vars["KCP_E2E_REST_PROXY_ENDPOINT"],
		DestClusterID:     vars["KCP_E2E_DEST_CLUSTER_ID"],
		ClusterAPIKey:     vars["KCP_E2E_CLUSTER_API_KEY"],
		ClusterAPISecret:  vars["KCP_E2E_CLUSTER_API_SECRET"],
		KCPPod:            vars["KCP_E2E_KCP_POD"],
		KubePath:          vars["KCP_E2E_KUBE_PATH"],

		Scenario:        scenario,
		ClusterLinkName: vars[prefix+"CLUSTER_LINK_NAME"],
		TopicName:       topicName,
		TopicNames:      topicNames,
		GatewayName:     vars[prefix+"GATEWAY_NAME"],
		FencedCR:        vars[prefix+"FENCED_CR"],
		SwitchoverCR:    vars[prefix+"SWITCHOVER_CR"],
	}
}

func testdataDir() string {
	// integration-tests/migration/ -> integration-tests/migration/testdata/
	return filepath.Join("testdata")
}

// runKCP executes the kcp binary inside the runner pod via kubectl exec.
func runKCP(t *testing.T, cfg envConfig, args ...string) (string, string, error) {
	t.Helper()

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Minute)
	defer cancel()

	kubectlArgs := []string{
		"--context", cfg.KubeContext,
		"-n", cfg.Namespace,
		"exec", cfg.KCPPod, "--",
		"/workspace/kcp",
	}
	kubectlArgs = append(kubectlArgs, args...)

	cmd := exec.CommandContext(ctx, "kubectl", kubectlArgs...)
	var stdout, stderr strings.Builder
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr

	err := cmd.Run()
	return stdout.String(), stderr.String(), err
}

// readPodFile reads a file from inside the runner pod.
func readPodFile(t *testing.T, cfg envConfig, podPath string) []byte {
	t.Helper()

	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	cmd := exec.CommandContext(ctx, "kubectl",
		"--context", cfg.KubeContext,
		"-n", cfg.Namespace,
		"exec", cfg.KCPPod, "--",
		"cat", podPath)
	var stderr strings.Builder
	cmd.Stderr = &stderr
	out, err := cmd.Output()
	require.NoError(t, err, "failed to read %s from pod: %s", podPath, stderr.String())
	return out
}

// gatewayGVR is the GroupVersionResource for Confluent Gateway CRs.
var gatewayGVR = schema.GroupVersionResource{
	Group:    "platform.confluent.io",
	Version:  "v1beta1",
	Resource: "gateways",
}

func getGatewayCR(t *testing.T, dynClient dynamic.Interface, namespace, name string) *unstructured.Unstructured {
	t.Helper()

	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	cr, err := dynClient.Resource(gatewayGVR).Namespace(namespace).Get(ctx, name, metav1.GetOptions{})
	require.NoError(t, err, "failed to get Gateway CR %s/%s", namespace, name)

	return cr
}

// assertGatewaySpec asserts the live Gateway CR has no fence on its route and
// points at the given streaming domain — the two fields that distinguish the
// initial ("source-kafka-cluster"), fenced, and switchover
// ("destination-kafka-cluster") specs.
func assertGatewaySpec(t *testing.T, dynClient dynamic.Interface, namespace, name, wantDomain string) {
	t.Helper()

	cr := getGatewayCR(t, dynClient, namespace, name)

	spec, found, err := unstructured.NestedMap(cr.Object, "spec")
	require.NoError(t, err)
	require.True(t, found, "spec not found in Gateway CR")

	routes, found, err := unstructured.NestedSlice(spec, "routes")
	require.NoError(t, err)
	require.True(t, found, "routes not found in spec")
	require.Len(t, routes, 1)

	route, ok := routes[0].(map[string]interface{})
	require.True(t, ok, "expected route to be a map")
	_, hasFence := route["fence"]
	assert.False(t, hasFence, "Gateway CR must not have fence config")

	streamingDomains, found, err := unstructured.NestedSlice(spec, "streamingDomains")
	require.NoError(t, err)
	require.True(t, found)
	require.Len(t, streamingDomains, 1)

	domain, ok := streamingDomains[0].(map[string]interface{})
	require.True(t, ok, "expected streaming domain to be a map")
	domainName, _, _ := unstructured.NestedString(domain, "name")
	assert.Equal(t, wantDomain, domainName, "Gateway CR must point at the %s streaming domain", wantDomain)
}

func getGatewayPodUIDs(t *testing.T, clientset kubernetes.Interface, namespace, gatewayName string) map[string]struct{} {
	t.Helper()

	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	pods, err := clientset.CoreV1().Pods(namespace).List(ctx, metav1.ListOptions{
		LabelSelector: fmt.Sprintf("app=%s", gatewayName),
	})
	require.NoError(t, err)

	uids := make(map[string]struct{}, len(pods.Items))
	for _, pod := range pods.Items {
		uids[string(pod.UID)] = struct{}{}
	}
	return uids
}

// migrationState mirrors the state file structure for assertion purposes.
type migrationState struct {
	Migrations []migrationConfig `json:"migrations"`
}

type migrationConfig struct {
	MigrationID                    string            `json:"migration_id"`
	CurrentState                   string            `json:"current_state"`
	PauseConsumerOffsetSync        bool              `json:"pause_consumer_offset_sync"`
	PauseConsumerOffsetSyncFlipped bool              `json:"pause_consumer_offset_sync_flipped"`
	ClusterLinkConfigs             map[string]string `json:"cluster_link_configs"`
}

// runInPodBackground starts a command inside the runner pod and returns
// immediately. The caller is responsible for terminating it via killInPod or
// waiting for the configured duration to elapse. Output is captured into
// /workspace/<basename>.log inside the pod for post-mortem inspection.
func runInPodBackground(t *testing.T, cfg envConfig, logName string, command ...string) {
	t.Helper()

	cmdline := strings.Join(command, " ")
	bgScript := fmt.Sprintf("(%s >/workspace/%s.log 2>&1 &)", cmdline, logName)

	out, err := runInPod(t, cfg, 30*time.Second, "sh", "-c", bgScript)
	if err != nil {
		t.Fatalf("failed to start background command %q: %v\n%s", cmdline, err, out)
	}
}

// killInPod terminates a process by name inside the runner pod. Ignored if the
// process is not running (the test may have already let it exit naturally).
func killInPod(t *testing.T, cfg envConfig, processName string) {
	t.Helper()
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	_ = exec.CommandContext(ctx, "kubectl",
		"--context", cfg.KubeContext,
		"-n", cfg.Namespace,
		"exec", cfg.KCPPod, "--",
		"pkill", "-f", processName,
	).Run()
}

// runInPod executes a command synchronously inside the runner pod and returns
// combined stdout/stderr plus any error.
func runInPod(t *testing.T, cfg envConfig, timeout time.Duration, command ...string) (string, error) {
	t.Helper()

	ctx, cancel := context.WithTimeout(context.Background(), timeout)
	defer cancel()

	args := []string{
		"--context", cfg.KubeContext,
		"-n", cfg.Namespace,
		"exec", cfg.KCPPod, "--",
	}
	args = append(args, command...)

	out, err := exec.CommandContext(ctx, "kubectl", args...).CombinedOutput()
	return string(out), err
}

// setClusterLinkConfig calls the in-pod setconfig helper to PUT a config
// value on the cluster link. Used by InitRefuses to flip the offset-sync
// setting without depending on curl (busybox wget cannot do PUT).
func setClusterLinkConfig(t *testing.T, cfg envConfig, name, value string) {
	t.Helper()
	out, err := runInPod(t, cfg, 30*time.Second,
		"/workspace/setconfig",
		"--url", cfg.RestProxyEndpoint,
		"--cluster", cfg.DestClusterID,
		"--link", cfg.ClusterLinkName,
		"--name", name,
		"--value", value,
		"--op", "SET",
	)
	require.NoError(t, err, "setconfig %s=%s failed:\n%s", name, value, out)
}

// getClusterLinkOffsetSyncEnable fetches the cluster link's
// consumer.offset.sync.enable value via the Kafka REST proxy reachable from
// inside the cluster. Returns the literal string ("true", "false", or "" if
// the key is missing). Used by tests to observe transitions during execute.
func getClusterLinkOffsetSyncEnable(t *testing.T, cfg envConfig) string {
	t.Helper()
	return getClusterLinkConfig(t, cfg, "consumer.offset.sync.enable")
}

// getClusterLinkOffsetSyncEnableSoft is the goroutine-safe variant: it
// returns (value, error) instead of calling require on a *testing.T. Use
// this inside background goroutines — Go's testing package documents
// FailNow/require as unsafe outside the test goroutine.
func getClusterLinkOffsetSyncEnableSoft(cfg envConfig) (string, error) {
	return getClusterLinkConfigSoft(cfg, "consumer.offset.sync.enable")
}

// getClusterLinkConfig is the generic variant: returns the value for any
// config key on the cluster link, or "" if missing.
func getClusterLinkConfig(t *testing.T, cfg envConfig, name string) string {
	t.Helper()
	v, err := getClusterLinkConfigSoft(cfg, name)
	require.NoError(t, err)
	return v
}

// getClusterLinkConfigSoft is the goroutine-safe generic variant. Returns
// (value, error) so callers can use it inside background goroutines without
// tripping the testing package's FailNow-from-goroutine rule.
func getClusterLinkConfigSoft(cfg envConfig, name string) (string, error) {
	configURL := fmt.Sprintf("%s/kafka/v3/clusters/%s/links/%s/configs", cfg.RestProxyEndpoint, cfg.DestClusterID, cfg.ClusterLinkName)
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	args := []string{
		"--context", cfg.KubeContext,
		"-n", cfg.Namespace,
		"exec", cfg.KCPPod, "--",
		"wget", "-qO-", configURL,
	}
	out, err := exec.CommandContext(ctx, "kubectl", args...).CombinedOutput()
	if err != nil {
		return "", fmt.Errorf("wget cluster link configs: %s: %w", out, err)
	}

	var resp struct {
		Data []struct {
			Name  string `json:"name"`
			Value string `json:"value"`
		} `json:"data"`
	}
	if err := json.Unmarshal(out, &resp); err != nil {
		return "", fmt.Errorf("unmarshalling configs response: %s: %w", out, err)
	}
	for _, c := range resp.Data {
		if c.Name == name {
			return c.Value, nil
		}
	}
	return "", nil
}

func readMigrationState(t *testing.T, cfg envConfig, podPath string) migrationState {
	t.Helper()

	data := readPodFile(t, cfg, podPath)

	var state migrationState
	require.NoError(t, json.Unmarshal(data, &state))

	return state
}

// mirrorTopicStatus is a single entry from the cluster link's mirrors listing.
type mirrorTopicStatus struct {
	Name   string
	Status string
}

// listMirrorTopics fetches the cluster link's mirror topics and their statuses
// via the destination Kafka REST proxy (reachable from inside the pod). Mirrors
// the endpoint kcp itself polls, so it observes the same ACTIVE/PENDING_STOPPED/
// STOPPED transitions.
func listMirrorTopics(cfg envConfig) ([]mirrorTopicStatus, error) {
	mirrorsURL := fmt.Sprintf("%s/kafka/v3/clusters/%s/links/%s/mirrors", cfg.RestProxyEndpoint, cfg.DestClusterID, cfg.ClusterLinkName)
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	args := []string{
		"--context", cfg.KubeContext,
		"-n", cfg.Namespace,
		"exec", cfg.KCPPod, "--",
		"wget", "-qO-", mirrorsURL,
	}
	out, err := exec.CommandContext(ctx, "kubectl", args...).CombinedOutput()
	if err != nil {
		return nil, fmt.Errorf("wget cluster link mirrors: %s: %w", out, err)
	}

	var resp struct {
		Data []struct {
			MirrorTopicName string `json:"mirror_topic_name"`
			MirrorStatus    string `json:"mirror_status"`
		} `json:"data"`
	}
	if err := json.Unmarshal(out, &resp); err != nil {
		return nil, fmt.Errorf("unmarshalling mirrors response: %s: %w", out, err)
	}

	result := make([]mirrorTopicStatus, 0, len(resp.Data))
	for _, d := range resp.Data {
		result = append(result, mirrorTopicStatus{Name: d.MirrorTopicName, Status: d.MirrorStatus})
	}
	return result, nil
}

// assertAllMirrorsStopped verifies that every expected topic's mirror reports
// the terminal STOPPED status. Polls briefly to absorb any REST eventual
// consistency (kcp gates on STOPPED, so this should already be true).
func assertAllMirrorsStopped(t *testing.T, cfg envConfig, expectedTopics []string) {
	t.Helper()

	deadline := time.Now().Add(30 * time.Second)
	var statusByName map[string]string
	for {
		mirrors, err := listMirrorTopics(cfg)
		require.NoError(t, err, "failed to list mirror topics")

		statusByName = make(map[string]string, len(mirrors))
		for _, m := range mirrors {
			statusByName[m.Name] = m.Status
		}

		allStopped := true
		for _, topic := range expectedTopics {
			if statusByName[topic] != "STOPPED" {
				allStopped = false
				break
			}
		}
		if allStopped || time.Now().After(deadline) {
			break
		}
		time.Sleep(2 * time.Second)
	}

	for _, topic := range expectedTopics {
		assert.Equal(t, "STOPPED", statusByName[topic],
			"mirror topic %q should be STOPPED after promotion (statuses: %v)", topic, statusByName)
	}
}

// podFileLineCount returns the number of lines in a file inside the runner pod,
// or 0 if the file does not exist. Used to snapshot kcp.log before an action so
// only the newly-appended lines are inspected afterward.
func podFileLineCount(t *testing.T, cfg envConfig, podPath string) int {
	t.Helper()
	out, err := runInPod(t, cfg, 30*time.Second, "sh", "-c",
		fmt.Sprintf("wc -l < %s 2>/dev/null || echo 0", podPath))
	if err != nil {
		return 0
	}
	n, _ := strconv.Atoi(strings.TrimSpace(out))
	return n
}

// readPodFileLinesFrom reads a file from the runner pod and returns the lines
// starting at startLine (0-indexed), i.e. the lines appended since a snapshot
// taken with podFileLineCount.
func readPodFileLinesFrom(t *testing.T, cfg envConfig, podPath string, startLine int) []string {
	t.Helper()
	data := readPodFile(t, cfg, podPath)
	lines := strings.Split(string(data), "\n")
	if startLine >= len(lines) {
		return nil
	}
	return lines[startLine:]
}

// Constants used by the producer/consumer subtests. Topic name comes from
// the scenario-resolved cfg.TopicName.
const (
	e2eProducerLog    = "producer"
	e2eConsumerGroup  = "kcp-e2e-consumer-group"
	e2eProducerBinary = "/workspace/producer"
	e2eConsumerBinary = "/workspace/consumer"
)

// startConsumerOnSource runs the consumer binary inside the pod to drain a
// few messages from the source cluster and commit offsets. Blocks until the
// consumer exits.
func startConsumerOnSource(t *testing.T, cfg envConfig, maxMessages int) {
	t.Helper()
	out, err := runInPod(t, cfg, 2*time.Minute,
		e2eConsumerBinary,
		"--bootstrap", cfg.SourceBootstrap,
		"--topic", cfg.TopicName,
		"--group", e2eConsumerGroup,
		"--max-messages", fmt.Sprintf("%d", maxMessages),
		"--timeout", "90s",
	)
	require.NoError(t, err, "consumer run failed:\n%s", out)
	t.Logf("consumer output:\n%s", out)
}

// startProducerOnSource starts the producer in the background. Caller must
// invoke stopProducer to terminate it.
func startProducerOnSource(t *testing.T, cfg envConfig, duration time.Duration) {
	t.Helper()
	runInPodBackground(t, cfg, e2eProducerLog,
		e2eProducerBinary,
		"--bootstrap", cfg.SourceBootstrap,
		"--topic", cfg.TopicName,
		"--duration", duration.String(),
		"--rate", "10",
	)
}

func stopProducer(t *testing.T, cfg envConfig) {
	t.Helper()
	killInPod(t, cfg, e2eProducerBinary)
}

// startProducerOnGateway starts the producer in the background pointed at the
// gateway's own proxy endpoint (not the raw source bootstrap) — legitimate,
// fully-migrated traffic that goes through the gateway rather than bypassing
// it. Caller must invoke stopProducer to terminate it.
func startProducerOnGateway(t *testing.T, cfg envConfig, duration time.Duration) {
	t.Helper()
	gatewayBootstrap := fmt.Sprintf("%s.%s.svc.cluster.local:9595", cfg.GatewayName, cfg.Namespace)
	runInPodBackground(t, cfg, e2eProducerLog,
		e2eProducerBinary,
		"--bootstrap", gatewayBootstrap,
		"--topic", cfg.TopicName,
		"--duration", duration.String(),
		"--rate", "20",
	)
}

func TestMigrationE2E(t *testing.T) {
	cfg := loadEnvConfig(t, scenarioBaseline)

	// Set up K8s clients for assertions (runs on host, uses host kubeconfig)
	kubeConfig, err := clientcmd.NewNonInteractiveDeferredLoadingClientConfig(
		&clientcmd.ClientConfigLoadingRules{ExplicitPath: cfg.Kubeconfig},
		&clientcmd.ConfigOverrides{CurrentContext: cfg.KubeContext},
	).ClientConfig()
	require.NoError(t, err, "failed to build kubeconfig")

	dynClient, err := dynamic.NewForConfig(kubeConfig)
	require.NoError(t, err)

	clientset, err := kubernetes.NewForConfig(kubeConfig)
	require.NoError(t, err)

	// State file lives inside the runner pod
	stateFile := "/workspace/migration-state.json"

	// Record Gateway pod UIDs before migration
	podUIDsBefore := getGatewayPodUIDs(t, clientset, cfg.Namespace, cfg.GatewayName)
	t.Logf("Gateway pods before migration: %d pods", len(podUIDsBefore))

	// --- Step 0: prime source with baseline producer + consumer offsets ---
	// The consumer commits offsets on the source pre-migration. With the
	// default migration flow (no --pause-consumer-offset-sync flag), the
	// cluster link will mirror these committed offsets to the destination.
	t.Run("seed_baseline_producer", func(t *testing.T) {
		// 10 quick records to give the consumer something to commit on.
		startProducerOnSource(t, cfg, 10*time.Second)
		// Let the producer get ahead of the consumer.
		time.Sleep(2 * time.Second)
	})

	t.Run("baseline_consumer_commits_offsets", func(t *testing.T) {
		startConsumerOnSource(t, cfg, 20)
	})

	t.Run("stop_baseline_producer", func(t *testing.T) {
		stopProducer(t, cfg)
	})

	// --- Step 1: kcp migration init ---
	t.Run("init", func(t *testing.T) {
		initArgs := []string{
			"migration", "init",
			"--source-bootstrap", cfg.SourceBootstrap,
			"--cluster-bootstrap", cfg.DestBootstrap,
			"--cluster-id", cfg.DestClusterID,
			"--cluster-rest-endpoint", cfg.RestProxyEndpoint,
			"--cluster-link-name", cfg.ClusterLinkName,
			"--cluster-api-key", cfg.ClusterAPIKey,
			"--cluster-api-secret", cfg.ClusterAPISecret,
			"--k8s-namespace", cfg.Namespace,
			"--initial-cr-name", cfg.GatewayName,
			"--fenced-cr-yaml", cfg.FencedCR,
			"--switchover-cr-yaml", cfg.SwitchoverCR,
			"--migration-state-file", stateFile,
			"--use-unauthenticated-plaintext",
			"--kube-path", cfg.KubePath,
			"--insecure-skip-tls-verify",
		}

		stdout, stderr, err := runKCP(t, cfg, initArgs...)
		t.Logf("init stdout:\n%s", stdout)
		t.Logf("init stderr:\n%s", stderr)
		require.NoError(t, err, "kcp migration init failed")

		// Assert: state file exists with initialized state
		state := readMigrationState(t, cfg, stateFile)
		require.Len(t, state.Migrations, 1, "expected exactly 1 migration")
		assert.Equal(t, "initialized", state.Migrations[0].CurrentState)
		t.Logf("Migration ID: %s", state.Migrations[0].MigrationID)
	})

	if t.Failed() {
		t.FailNow()
	}

	// --- Step 2: producer keeps writing during execute ---
	t.Run("start_producer_during_execute", func(t *testing.T) {
		startProducerOnSource(t, cfg, 5*time.Minute)
		// Give producer a moment to push records before kcp inspects lags.
		time.Sleep(2 * time.Second)
	})

	t.Cleanup(func() { stopProducer(t, cfg) })

	// --- Step 3: kcp migration execute ---
	t.Run("execute", func(t *testing.T) {
		// Get migration ID from state file
		state := readMigrationState(t, cfg, stateFile)
		require.Len(t, state.Migrations, 1)
		migrationID := state.Migrations[0].MigrationID

		executeArgs := []string{
			"migration", "execute",
			"--migration-id", migrationID,
			"--migration-state-file", stateFile,
			"--cluster-api-key", cfg.ClusterAPIKey,
			"--cluster-api-secret", cfg.ClusterAPISecret,
			"--lag-threshold", "0",
			"--use-unauthenticated-plaintext",
			"--insecure-skip-tls-verify",
			"--detect-unrouted-producers-duration", "0",
		}

		stdout, stderr, err := runKCP(t, cfg, executeArgs...)
		t.Logf("execute stdout:\n%s", stdout)
		t.Logf("execute stderr:\n%s", stderr)
		require.NoError(t, err, "kcp migration execute failed")

		// Assert: state file shows switched
		state = readMigrationState(t, cfg, stateFile)
		require.Len(t, state.Migrations, 1)
		assert.Equal(t, "switched", state.Migrations[0].CurrentState)

		// Without --pause-consumer-offset-sync the pause_offset_sync FSM
		// stage still fires as a pass-through and says so.
		assert.Contains(t, stdout, "Offset-sync pause not requested",
			"the pause stage must announce the pass-through path")
		assert.NotContains(t, stdout, "Pausing consumer.offset.sync",
			"the pause stage must not touch the cluster link without the flag")
	})

	if t.Failed() {
		t.FailNow()
	}

	// --- Step 2b: Verify mirror topics actually reached STOPPED ---
	// The migration only reports success once kcp confirms each promoted mirror
	// topic transitioned to the terminal STOPPED state (not merely that the
	// promote request was accepted). Assert that end state directly.
	t.Run("verify_mirror_topics_stopped", func(t *testing.T) {
		assertAllMirrorsStopped(t, cfg, cfg.TopicNames)
	})

	// --- Step 3: Verify Gateway CR matches switchover fixture ---
	t.Run("verify_gateway_cr", func(t *testing.T) {
		cr := getGatewayCR(t, dynClient, cfg.Namespace, cfg.GatewayName)

		// Extract spec.routes[0] for targeted field comparison
		spec, found, err := unstructured.NestedMap(cr.Object, "spec")
		require.NoError(t, err)
		require.True(t, found, "spec not found in Gateway CR")

		// Verify no fence config (switchover removes the fence)
		routes, found, err := unstructured.NestedSlice(spec, "routes")
		require.NoError(t, err)
		require.True(t, found, "routes not found in spec")
		require.Len(t, routes, 1)

		route, ok := routes[0].(map[string]interface{})
		require.True(t, ok, "expected route to be a map")
		_, hasFence := route["fence"]
		assert.False(t, hasFence, "switchover CR should not have fence config")

		// Verify streaming domain points to destination
		streamingDomains, found, err := unstructured.NestedSlice(spec, "streamingDomains")
		require.NoError(t, err)
		require.True(t, found)
		require.Len(t, streamingDomains, 1)

		domain, ok := streamingDomains[0].(map[string]interface{})
		require.True(t, ok, "expected streaming domain to be a map")
		domainName, _, _ := unstructured.NestedString(domain, "name")
		assert.Equal(t, "destination-kafka-cluster", domainName, "switchover should point to destination streaming domain")
	})

	if t.Failed() {
		t.FailNow()
	}

	// --- Step 4: Verify Gateway pods rolled out ---
	t.Run("verify_pod_rollout", func(t *testing.T) {
		podUIDsAfter := getGatewayPodUIDs(t, clientset, cfg.Namespace, cfg.GatewayName)
		t.Logf("Gateway pods after migration: %d pods", len(podUIDsAfter))

		// At least one pod UID should have changed (rollout occurred)
		allSame := true
		for uid := range podUIDsAfter {
			if _, existed := podUIDsBefore[uid]; !existed {
				allSame = false
				break
			}
		}
		assert.False(t, allSame, "expected Gateway pods to have rolled out (new UIDs)")
	})

	// --- Step 5: Regression for R18 — without the flag, kcp must not have
	// touched the cluster link's consumer.offset.sync.enable config.
	t.Run("offset_sync_unchanged", func(t *testing.T) {
		value := getClusterLinkOffsetSyncEnable(t, cfg)
		assert.Equal(t, "true", value, "without --pause-consumer-offset-sync, the cluster link config must remain true throughout the migration")
	})
}

// TestMigrationE2E_PromoteBatchSize exercises --promote-batch-size against a
// scenario whose cluster link mirrors many topics. With a batch size of 1, kcp
// must promote one topic at a time, waiting for each to reach STOPPED before
// promoting the next — i.e. fully synchronous batches. Asserts:
//   - the migration reaches switched,
//   - every mirror topic reaches STOPPED,
//   - kcp.log shows one single-topic promote call per topic (no bulk promote),
//     and one STOPPED confirmation per topic.
//
// Runs against the dedicated "batch" scenario provisioned by setup.sh.
func TestMigrationE2E_PromoteBatchSize(t *testing.T) {
	cfg := loadEnvConfig(t, scenarioBatch)
	require.GreaterOrEqual(t, len(cfg.TopicNames), 2,
		"batch scenario must provision multiple topics (got %v)", cfg.TopicNames)

	stateFile := "/workspace/migration-state-batch.json"
	const logPath = "/workspace/kcp.log"

	// --- Step 1: init ---
	t.Run("init", func(t *testing.T) {
		initArgs := []string{
			"migration", "init",
			"--source-bootstrap", cfg.SourceBootstrap,
			"--cluster-bootstrap", cfg.DestBootstrap,
			"--cluster-id", cfg.DestClusterID,
			"--cluster-rest-endpoint", cfg.RestProxyEndpoint,
			"--cluster-link-name", cfg.ClusterLinkName,
			"--cluster-api-key", cfg.ClusterAPIKey,
			"--cluster-api-secret", cfg.ClusterAPISecret,
			"--k8s-namespace", cfg.Namespace,
			"--initial-cr-name", cfg.GatewayName,
			"--fenced-cr-yaml", cfg.FencedCR,
			"--switchover-cr-yaml", cfg.SwitchoverCR,
			"--migration-state-file", stateFile,
			"--use-unauthenticated-plaintext",
			"--kube-path", cfg.KubePath,
			"--insecure-skip-tls-verify",
		}

		stdout, stderr, err := runKCP(t, cfg, initArgs...)
		t.Logf("init stdout:\n%s", stdout)
		t.Logf("init stderr:\n%s", stderr)
		require.NoError(t, err, "kcp migration init failed")

		state := readMigrationState(t, cfg, stateFile)
		require.Len(t, state.Migrations, 1)
		assert.Equal(t, "initialized", state.Migrations[0].CurrentState)
	})

	if t.Failed() {
		t.FailNow()
	}

	// Snapshot kcp.log so the batching assertion only inspects the execute run.
	logStart := podFileLineCount(t, cfg, logPath)

	// --- Step 2: execute with --promote-batch-size 1 ---
	t.Run("execute_batched", func(t *testing.T) {
		state := readMigrationState(t, cfg, stateFile)
		require.Len(t, state.Migrations, 1)
		migrationID := state.Migrations[0].MigrationID

		executeArgs := []string{
			"migration", "execute",
			"--migration-id", migrationID,
			"--migration-state-file", stateFile,
			"--cluster-api-key", cfg.ClusterAPIKey,
			"--cluster-api-secret", cfg.ClusterAPISecret,
			"--lag-threshold", "0",
			"--promote-batch-size", "1",
			"--use-unauthenticated-plaintext",
			"--insecure-skip-tls-verify",
			// Required flag; 0 because this scenario's producer writes directly
			// to the source brokers and would otherwise trip detection.
			"--detect-unrouted-producers-duration", "0",
		}

		stdout, stderr, err := runKCP(t, cfg, executeArgs...)
		t.Logf("execute stdout:\n%s", stdout)
		t.Logf("execute stderr:\n%s", stderr)
		require.NoError(t, err, "kcp migration execute failed")

		state = readMigrationState(t, cfg, stateFile)
		require.Len(t, state.Migrations, 1)
		assert.Equal(t, "switched", state.Migrations[0].CurrentState)
	})

	if t.Failed() {
		t.FailNow()
	}

	// --- Step 3: every mirror topic reached STOPPED ---
	t.Run("all_mirrors_stopped", func(t *testing.T) {
		assertAllMirrorsStopped(t, cfg, cfg.TopicNames)
	})

	// --- Step 4: promotion ran as sequential single-topic batches ---
	t.Run("promoted_in_single_topic_batches", func(t *testing.T) {
		lines := readPodFileLinesFrom(t, cfg, logPath, logStart)
		require.NotEmpty(t, lines, "expected new kcp.log lines from the execute run")

		var singleTopicPromotes, bulkPromotes, stoppedConfirms int
		for _, ln := range lines {
			if strings.Contains(ln, "promoting mirror topics") {
				if strings.Contains(ln, "topicCount=1 topics=") {
					singleTopicPromotes++
				} else {
					bulkPromotes++
				}
			}
			if strings.Contains(ln, "mirror topic promotion confirmed stopped") {
				stoppedConfirms++
			}
		}

		n := len(cfg.TopicNames)
		assert.Equal(t, n, singleTopicPromotes,
			"expected exactly one single-topic promote call per topic with --promote-batch-size 1")
		assert.Zero(t, bulkPromotes,
			"no promote call should contain more than one topic with --promote-batch-size 1")
		assert.Equal(t, n, stoppedConfirms,
			"each promoted topic should be individually confirmed STOPPED")
	})
}

// TestMigrationE2E_PauseOffsetSync_HappyPath exercises the full
// --pause-consumer-offset-sync flow: init records intent, execute disables
// the config from the pause_offset_sync FSM stage (immediately after
// fencing, so destination offsets stay fresh through the lag and fence
// phases), runs the migration, then restores the config after switchover.
// Asserts the true → false → true transition is observable via ListConfigs
// polling.
//
// Runs against the "pause-sync-happy" scenario — its own dedicated source
// topic, cluster link, and gateway CR provisioned by setup.sh — so it is
// independent of TestMigrationE2E.
func TestMigrationE2E_PauseOffsetSync_HappyPath(t *testing.T) {
	cfg := loadEnvConfig(t, scenarioPauseSyncHappy)

	stateFile := "/workspace/migration-state-pause-sync-happy.json"

	// Make sure no leftover producer is running from a prior test.
	stopProducer(t, cfg)

	// Sanity check: cluster link starts with enable=true.
	startValue := getClusterLinkOffsetSyncEnable(t, cfg)
	require.Equal(t, "true", startValue, "fixture must start with consumer.offset.sync.enable=true")

	// Pre-existing consumer commits on the source so we have a non-zero
	// committed offset that would, in the default flow, be mirrored to dest.
	t.Run("seed_baseline", func(t *testing.T) {
		startProducerOnSource(t, cfg, 10*time.Second)
		time.Sleep(2 * time.Second)
		startConsumerOnSource(t, cfg, 20)
		stopProducer(t, cfg)
	})

	// --- Step 1: init with the flag ---
	t.Run("init_with_flag", func(t *testing.T) {
		initArgs := []string{
			"migration", "init",
			"--source-bootstrap", cfg.SourceBootstrap,
			"--cluster-bootstrap", cfg.DestBootstrap,
			"--cluster-id", cfg.DestClusterID,
			"--cluster-rest-endpoint", cfg.RestProxyEndpoint,
			"--cluster-link-name", cfg.ClusterLinkName,
			"--cluster-api-key", cfg.ClusterAPIKey,
			"--cluster-api-secret", cfg.ClusterAPISecret,
			"--k8s-namespace", cfg.Namespace,
			"--initial-cr-name", cfg.GatewayName,
			"--fenced-cr-yaml", cfg.FencedCR,
			"--switchover-cr-yaml", cfg.SwitchoverCR,
			"--migration-state-file", stateFile,
			"--use-unauthenticated-plaintext",
			"--kube-path", cfg.KubePath,
			"--insecure-skip-tls-verify",
			"--pause-consumer-offset-sync",
		}

		stdout, stderr, err := runKCP(t, cfg, initArgs...)
		t.Logf("init stdout:\n%s", stdout)
		t.Logf("init stderr:\n%s", stderr)
		require.NoError(t, err, "kcp migration init failed")

		state := readMigrationState(t, cfg, stateFile)
		require.Len(t, state.Migrations, 1)
		assert.True(t, state.Migrations[0].PauseConsumerOffsetSync, "intent must persist")
		assert.False(t, state.Migrations[0].PauseConsumerOffsetSyncFlipped, "marker must NOT be flipped at init time")
	})

	// After init the config should STILL be true — init only records intent.
	t.Run("config_still_true_after_init", func(t *testing.T) {
		assert.Equal(t, "true", getClusterLinkOffsetSyncEnable(t, cfg))
	})

	// --- Step 2: producer running during execute ---
	t.Run("start_producer", func(t *testing.T) {
		startProducerOnSource(t, cfg, 5*time.Minute)
		time.Sleep(2 * time.Second)
	})
	t.Cleanup(func() { stopProducer(t, cfg) })

	// Best-effort polling of the live cluster-link config alongside execute.
	// This is purely advisory: it produces a log line showing the observed
	// true→false→true sequence when timing permits, but a fast FSM run may
	// not catch the disabled window. The deterministic check is on the
	// bookend's stdout lines (asserted below). The goroutine uses the Soft
	// variant because require.NoError on the parent *testing.T is unsafe
	// from a non-test goroutine — transient wget/JSON errors are swallowed
	// locally instead of crashing the test.
	configObservations := make(chan string, 100)
	pollCtx, cancelPoll := context.WithCancel(context.Background())
	pollDone := make(chan struct{})
	go func() {
		defer close(pollDone)
		ticker := time.NewTicker(200 * time.Millisecond)
		defer ticker.Stop()
		for {
			select {
			case <-pollCtx.Done():
				return
			case <-ticker.C:
				v, err := getClusterLinkOffsetSyncEnableSoft(cfg)
				if err != nil {
					continue
				}
				select {
				case configObservations <- v:
				default:
				}
			}
		}
	}()

	var executeStdout string
	t.Run("execute_with_flag", func(t *testing.T) {
		state := readMigrationState(t, cfg, stateFile)
		require.Len(t, state.Migrations, 1)
		migrationID := state.Migrations[0].MigrationID

		executeArgs := []string{
			"migration", "execute",
			"--migration-id", migrationID,
			"--migration-state-file", stateFile,
			"--cluster-api-key", cfg.ClusterAPIKey,
			"--cluster-api-secret", cfg.ClusterAPISecret,
			"--lag-threshold", "0",
			"--use-unauthenticated-plaintext",
			"--insecure-skip-tls-verify",
			"--detect-unrouted-producers-duration", "0",
		}

		stdout, stderr, err := runKCP(t, cfg, executeArgs...)
		executeStdout = stdout
		t.Logf("execute stdout:\n%s", stdout)
		t.Logf("execute stderr:\n%s", stderr)
		require.NoError(t, err, "kcp migration execute failed")

		state = readMigrationState(t, cfg, stateFile)
		require.Len(t, state.Migrations, 1)
		assert.Equal(t, "switched", state.Migrations[0].CurrentState)
		assert.False(t, state.Migrations[0].PauseConsumerOffsetSyncFlipped, "marker must clear after successful restore")
	})

	cancelPoll()
	<-pollDone

	// Log the observed sequence (advisory only — see comment on the poller).
	close(configObservations)
	seen := []string{}
	for v := range configObservations {
		if len(seen) == 0 || seen[len(seen)-1] != v {
			seen = append(seen, v)
		}
	}
	t.Logf("observed cluster-link config sequence during execute (advisory): %v", seen)

	// --- Step 3: deterministic assertions ---
	t.Run("bookend_ran_and_final_state_restored", func(t *testing.T) {
		// The pause stage and restore bookend print these lines
		// unconditionally when they run. They are durable evidence that the
		// disable→restore cycle executed, without depending on poll timing
		// landing inside the FSM window.
		assert.Contains(t, executeStdout, "Pausing consumer.offset.sync",
			"execute stdout must show the pause stage ran")
		assert.Contains(t, executeStdout, "Restoring consumer.offset.sync",
			"execute stdout must show the restore bookend ran")

		// The pause is an FSM stage that fires AFTER fencing — stdout order
		// pins the re-timing (previously the disable ran before the FSM).
		fenceIdx := strings.Index(executeStdout, "Fencing gateway")
		pauseIdx := strings.Index(executeStdout, "Pausing consumer.offset.sync")
		require.NotEqual(t, -1, fenceIdx, "execute stdout must show the fence step")
		require.NotEqual(t, -1, pauseIdx, "execute stdout must show the pause stage")
		assert.Less(t, fenceIdx, pauseIdx,
			"the pause must fire after fencing, not as a pre-FSM bookend")

		// And the live cluster link must be back to enable=true.
		assert.Equal(t, "true", getClusterLinkOffsetSyncEnable(t, cfg),
			"final state must be restored to true")
	})
}

// TestMigrationE2E_PauseOffsetSync_Drain verifies the
// --consumer-offset-sync-drain-duration flag end-to-end: with
// --pause-consumer-offset-sync set, execute holds after fencing (sync still
// enabled) for the drain duration before disabling consumer.offset.sync.enable,
// then completes the switchover and restores the config.
//
// Scope note: this proves the drain PATH runs against a real cluster link and
// does not regress the offset-sync round-trip — it deliberately does NOT try to
// prove a reduction in duplicate processing. That effect is timing/probabilistic
// against the cluster link's asynchronous sync scheduler, which this harness
// cannot observe deterministically (see the advisory-only config poller in
// TestMigrationE2E_PauseOffsetSync_HappyPath). The deterministic evidence here
// is the ordered stdout (fence → pause → drain → disable) plus a wall-clock
// lower bound.
//
// Runs against the dedicated "pause-sync-drain" scenario provisioned by
// setup.sh, so it is independent of the other pause-sync tests.
func TestMigrationE2E_PauseOffsetSync_Drain(t *testing.T) {
	cfg := loadEnvConfig(t, scenarioPauseSyncDrain)

	stateFile := "/workspace/migration-state-pause-sync-drain.json"

	const drain = 15 * time.Second

	// No leftover producer from a prior test.
	stopProducer(t, cfg)

	// Sanity: cluster link starts enabled.
	require.Equal(t, "true", getClusterLinkOffsetSyncEnable(t, cfg),
		"fixture must start with consumer.offset.sync.enable=true")

	// Seed a committed consumer offset on the source so there is a real offset
	// in play during the migration.
	t.Run("seed_baseline", func(t *testing.T) {
		startProducerOnSource(t, cfg, 10*time.Second)
		time.Sleep(2 * time.Second)
		startConsumerOnSource(t, cfg, 20)
		stopProducer(t, cfg)
	})

	// Init with the pause flag (the drain is an execute-time flag).
	t.Run("init_with_pause_flag", func(t *testing.T) {
		initArgs := []string{
			"migration", "init",
			"--source-bootstrap", cfg.SourceBootstrap,
			"--cluster-bootstrap", cfg.DestBootstrap,
			"--cluster-id", cfg.DestClusterID,
			"--cluster-rest-endpoint", cfg.RestProxyEndpoint,
			"--cluster-link-name", cfg.ClusterLinkName,
			"--cluster-api-key", cfg.ClusterAPIKey,
			"--cluster-api-secret", cfg.ClusterAPISecret,
			"--k8s-namespace", cfg.Namespace,
			"--initial-cr-name", cfg.GatewayName,
			"--fenced-cr-yaml", cfg.FencedCR,
			"--switchover-cr-yaml", cfg.SwitchoverCR,
			"--migration-state-file", stateFile,
			"--use-unauthenticated-plaintext",
			"--kube-path", cfg.KubePath,
			"--insecure-skip-tls-verify",
			"--pause-consumer-offset-sync",
		}
		stdout, stderr, err := runKCP(t, cfg, initArgs...)
		t.Logf("init stdout:\n%s", stdout)
		t.Logf("init stderr:\n%s", stderr)
		require.NoError(t, err, "kcp migration init failed")
	})

	var executeStdout string
	var executeElapsed time.Duration
	t.Run("execute_with_drain", func(t *testing.T) {
		state := readMigrationState(t, cfg, stateFile)
		require.Len(t, state.Migrations, 1)
		migrationID := state.Migrations[0].MigrationID

		executeArgs := []string{
			"migration", "execute",
			"--migration-id", migrationID,
			"--migration-state-file", stateFile,
			"--cluster-api-key", cfg.ClusterAPIKey,
			"--cluster-api-secret", cfg.ClusterAPISecret,
			"--lag-threshold", "0",
			"--use-unauthenticated-plaintext",
			"--insecure-skip-tls-verify",
			"--detect-unrouted-producers-duration", "0",
			"--consumer-offset-sync-drain-duration", drain.String(),
		}

		start := time.Now()
		stdout, stderr, err := runKCP(t, cfg, executeArgs...)
		executeElapsed = time.Since(start)
		executeStdout = stdout
		t.Logf("execute stdout:\n%s", stdout)
		t.Logf("execute stderr:\n%s", stderr)
		require.NoError(t, err, "kcp migration execute failed")

		state = readMigrationState(t, cfg, stateFile)
		require.Len(t, state.Migrations, 1)
		assert.Equal(t, "switched", state.Migrations[0].CurrentState)
		assert.False(t, state.Migrations[0].PauseConsumerOffsetSyncFlipped,
			"marker must clear after successful restore")
	})

	// Deterministic evidence: the drain line prints unconditionally when the
	// flag is set, and stdout order pins it between the pause stage and the
	// actual disable — i.e. sync was still enabled while the drain held.
	t.Run("drain_ran_between_fence_and_disable", func(t *testing.T) {
		fenceIdx := strings.Index(executeStdout, "Fencing gateway")
		pauseIdx := strings.Index(executeStdout, "Pausing consumer.offset.sync")
		drainIdx := strings.Index(executeStdout, "Draining consumer offset sync")
		disableIdx := strings.Index(executeStdout, "set to false")

		require.NotEqual(t, -1, fenceIdx, "stdout must show the fence step")
		require.NotEqual(t, -1, pauseIdx, "stdout must show the pause stage")
		require.NotEqual(t, -1, drainIdx, "stdout must show the drain line — the flag had no effect")
		require.NotEqual(t, -1, disableIdx, "stdout must show the disable success line")

		assert.Less(t, fenceIdx, pauseIdx, "pause must fire after fencing")
		assert.Less(t, pauseIdx, drainIdx, "drain must come after the pause stage header")
		assert.Less(t, drainIdx, disableIdx, "drain must complete before sync is disabled")
	})

	// Lower-bound sanity check that the wait actually happened live. Other
	// phases add time, so this only guards against the drain being skipped.
	t.Run("execute_waited_at_least_the_drain", func(t *testing.T) {
		assert.GreaterOrEqual(t, executeElapsed, drain,
			"execute wall-clock (%s) must be at least the drain duration (%s)", executeElapsed, drain)
	})

	t.Run("config_restored_to_true", func(t *testing.T) {
		assert.Equal(t, "true", getClusterLinkOffsetSyncEnable(t, cfg),
			"final state must be restored to true")
	})
}

// TestMigrationE2E_PauseOffsetSync_InitRefuses verifies that when the
// cluster link's consumer.offset.sync.enable is NOT "true", init with the
// flag exits non-zero with a useful message.
//
// Runs against the "pause-sync-refuses" scenario, which gives this test
// its own cluster link so flipping offset-sync to "false" does not leak
// into other tests.
func TestMigrationE2E_PauseOffsetSync_InitRefuses(t *testing.T) {
	cfg := loadEnvConfig(t, scenarioPauseSyncRefuses)

	setClusterLinkConfig(t, cfg, "consumer.offset.sync.enable", "false")
	t.Cleanup(func() {
		setClusterLinkConfig(t, cfg, "consumer.offset.sync.enable", "true")
	})

	// Best-effort wait for the config to propagate.
	for i := 0; i < 10; i++ {
		if getClusterLinkOffsetSyncEnable(t, cfg) == "false" {
			break
		}
		time.Sleep(500 * time.Millisecond)
	}
	require.Equal(t, "false", getClusterLinkOffsetSyncEnable(t, cfg), "fixture must be flipped to false before this test runs")

	stateFile := "/workspace/migration-state-refuse.json"

	initArgs := []string{
		"migration", "init",
		"--source-bootstrap", cfg.SourceBootstrap,
		"--cluster-bootstrap", cfg.DestBootstrap,
		"--cluster-id", cfg.DestClusterID,
		"--cluster-rest-endpoint", cfg.RestProxyEndpoint,
		"--cluster-link-name", cfg.ClusterLinkName,
		"--cluster-api-key", cfg.ClusterAPIKey,
		"--cluster-api-secret", cfg.ClusterAPISecret,
		"--k8s-namespace", cfg.Namespace,
		"--initial-cr-name", cfg.GatewayName,
		"--fenced-cr-yaml", cfg.FencedCR,
		"--switchover-cr-yaml", cfg.SwitchoverCR,
		"--migration-state-file", stateFile,
		"--use-unauthenticated-plaintext",
		"--kube-path", cfg.KubePath,
		"--insecure-skip-tls-verify",
		"--pause-consumer-offset-sync",
	}

	stdout, stderr, err := runKCP(t, cfg, initArgs...)
	t.Logf("init stdout:\n%s", stdout)
	t.Logf("init stderr:\n%s", stderr)
	require.Error(t, err, "init must fail when cluster link offset sync is not true")
	combined := stdout + stderr
	assert.Contains(t, combined, cfg.ClusterLinkName, "error must name the cluster link")
	assert.Contains(t, combined, "consumer.offset.sync.enable", "error must name the config key")
}

// TestMigrationE2E_PauseOffsetSync_RestoresFilters verifies that a
// consumer.offset.group.filters value configured on the cluster link before
// init is preserved across the --pause-consumer-offset-sync round-trip.
//
// The bookend exists because setting consumer.offset.sync.enable=false on a
// cluster link clears consumer.offset.group.filters as a side effect on both
// Confluent Cloud and Confluent Platform. The disable bookend triggers that
// clearing; the restore bookend re-applies filters from the init-time
// snapshot. This test exercises that round-trip end-to-end.
//
// Runs against the "pause-sync-restores-filters" scenario — its own
// dedicated source topic, cluster link, and gateway CR provisioned by
// setup.sh — so it is independent of the other migration tests.
func TestMigrationE2E_PauseOffsetSync_RestoresFilters(t *testing.T) {
	cfg := loadEnvConfig(t, scenarioPauseSyncRestoresFilters)

	stateFile := "/workspace/migration-state-pause-sync-restores-filters.json"
	stopProducer(t, cfg)

	const filtersKey = "consumer.offset.group.filters"
	const filtersValue = `{"groupFilters":[{"name":"e2e-*","patternType":"PREFIXED","filterType":"INCLUDE"}]}`

	// Pre-populate filters on the cluster link before init so the snapshot
	// captures the value. setClusterLinkConfig fails the test if the CP REST
	// API rejects the PUT (e.g. malformed JSON or unsupported key on this CP
	// version) — a clear signal that the fixture or CP version needs
	// adjustment.
	setClusterLinkConfig(t, cfg, filtersKey, filtersValue)

	// Sanity checks: fixture matches expectations before init runs.
	require.Equal(t, "true", getClusterLinkOffsetSyncEnable(t, cfg), "fixture must start with consumer.offset.sync.enable=true")
	require.Equal(t, filtersValue, getClusterLinkConfig(t, cfg, filtersKey), "fixture must have filters set before init")

	// --- Step 1: init with the flag ---
	t.Run("init_captures_filters_snapshot", func(t *testing.T) {
		initArgs := []string{
			"migration", "init",
			"--source-bootstrap", cfg.SourceBootstrap,
			"--cluster-bootstrap", cfg.DestBootstrap,
			"--cluster-id", cfg.DestClusterID,
			"--cluster-rest-endpoint", cfg.RestProxyEndpoint,
			"--cluster-link-name", cfg.ClusterLinkName,
			"--cluster-api-key", cfg.ClusterAPIKey,
			"--cluster-api-secret", cfg.ClusterAPISecret,
			"--k8s-namespace", cfg.Namespace,
			"--initial-cr-name", cfg.GatewayName,
			"--fenced-cr-yaml", cfg.FencedCR,
			"--switchover-cr-yaml", cfg.SwitchoverCR,
			"--migration-state-file", stateFile,
			"--use-unauthenticated-plaintext",
			"--kube-path", cfg.KubePath,
			"--insecure-skip-tls-verify",
			"--pause-consumer-offset-sync",
		}

		stdout, stderr, err := runKCP(t, cfg, initArgs...)
		t.Logf("init stdout:\n%s", stdout)
		t.Logf("init stderr:\n%s", stderr)
		require.NoError(t, err, "kcp migration init failed")

		state := readMigrationState(t, cfg, stateFile)
		require.Len(t, state.Migrations, 1)
		assert.True(t, state.Migrations[0].PauseConsumerOffsetSync, "intent must persist")
		assert.False(t, state.Migrations[0].PauseConsumerOffsetSyncFlipped, "marker must NOT be flipped at init time")
		assert.Equal(t, filtersValue, state.Migrations[0].ClusterLinkConfigs[filtersKey],
			"init must capture filters value in the ClusterLinkConfigs snapshot — restore reads from this")
	})

	// --- Step 2: producer running during execute ---
	t.Run("start_producer", func(t *testing.T) {
		startProducerOnSource(t, cfg, 5*time.Minute)
		time.Sleep(2 * time.Second)
	})
	t.Cleanup(func() { stopProducer(t, cfg) })

	// --- Step 3: execute ---
	t.Run("execute_with_flag", func(t *testing.T) {
		state := readMigrationState(t, cfg, stateFile)
		require.Len(t, state.Migrations, 1)
		migrationID := state.Migrations[0].MigrationID

		executeArgs := []string{
			"migration", "execute",
			"--migration-id", migrationID,
			"--migration-state-file", stateFile,
			"--cluster-api-key", cfg.ClusterAPIKey,
			"--cluster-api-secret", cfg.ClusterAPISecret,
			"--lag-threshold", "0",
			"--use-unauthenticated-plaintext",
			"--insecure-skip-tls-verify",
			"--detect-unrouted-producers-duration", "0",
		}

		stdout, stderr, err := runKCP(t, cfg, executeArgs...)
		t.Logf("execute stdout:\n%s", stdout)
		t.Logf("execute stderr:\n%s", stderr)
		require.NoError(t, err, "kcp migration execute failed")

		state = readMigrationState(t, cfg, stateFile)
		require.Len(t, state.Migrations, 1)
		assert.Equal(t, "switched", state.Migrations[0].CurrentState)
		assert.False(t, state.Migrations[0].PauseConsumerOffsetSyncFlipped, "marker must clear after successful restore")
	})

	// --- Step 4: post-migration parity ---
	t.Run("filters_match_init_snapshot", func(t *testing.T) {
		assert.Equal(t, "true", getClusterLinkOffsetSyncEnable(t, cfg), "toggle must be restored to true")
		assert.Equal(t, filtersValue, getClusterLinkConfig(t, cfg, filtersKey),
			"%s must match the value set before init — this is the restore bookend's primary contract", filtersKey)
	})
}

// TestMigrationE2E_RogueProducerDetection exercises the unrouted-producer
// safety check against real infrastructure.
//
// Phase A: a producer writing directly to the source brokers (bypassing the
// gateway) must trip detection after fencing. Execute fails, the FSM rolls
// back to initialized via abort_fence, and the live Gateway CR is restored to
// its initial (unfenced) spec — the only end-to-end validation that the real
// Confluent operator accepts the re-applied initial CR (server metadata
// stripped) on rollback.
//
// Phase B: with the rogue producer stopped, re-running execute re-verifies
// the fence (source offsets stable) and completes the migration to switched.
func TestMigrationE2E_RogueProducerDetection(t *testing.T) {
	cfg := loadEnvConfig(t, scenarioRogueProducer)

	kubeConfig, err := clientcmd.NewNonInteractiveDeferredLoadingClientConfig(
		&clientcmd.ClientConfigLoadingRules{ExplicitPath: cfg.Kubeconfig},
		&clientcmd.ConfigOverrides{CurrentContext: cfg.KubeContext},
	).ClientConfig()
	require.NoError(t, err, "failed to build kubeconfig")

	dynClient, err := dynamic.NewForConfig(kubeConfig)
	require.NoError(t, err)

	clientset, err := kubernetes.NewForConfig(kubeConfig)
	require.NoError(t, err)

	stateFile := "/workspace/migration-state-rogue-producer.json"

	// --- Step 0: seed the source topic so the link has data to mirror ---
	t.Run("seed_source_topic", func(t *testing.T) {
		startProducerOnSource(t, cfg, 10*time.Second)
		time.Sleep(2 * time.Second)
		stopProducer(t, cfg)
	})

	// --- Step 1: kcp migration init ---
	t.Run("init", func(t *testing.T) {
		initArgs := []string{
			"migration", "init",
			"--source-bootstrap", cfg.SourceBootstrap,
			"--cluster-bootstrap", cfg.DestBootstrap,
			"--cluster-id", cfg.DestClusterID,
			"--cluster-rest-endpoint", cfg.RestProxyEndpoint,
			"--cluster-link-name", cfg.ClusterLinkName,
			"--cluster-api-key", cfg.ClusterAPIKey,
			"--cluster-api-secret", cfg.ClusterAPISecret,
			"--k8s-namespace", cfg.Namespace,
			"--initial-cr-name", cfg.GatewayName,
			"--fenced-cr-yaml", cfg.FencedCR,
			"--switchover-cr-yaml", cfg.SwitchoverCR,
			"--migration-state-file", stateFile,
			"--use-unauthenticated-plaintext",
			"--kube-path", cfg.KubePath,
			"--insecure-skip-tls-verify",
		}

		stdout, stderr, err := runKCP(t, cfg, initArgs...)
		t.Logf("init stdout:\n%s", stdout)
		t.Logf("init stderr:\n%s", stderr)
		require.NoError(t, err, "kcp migration init failed")

		state := readMigrationState(t, cfg, stateFile)
		require.Len(t, state.Migrations, 1)
		assert.Equal(t, "initialized", state.Migrations[0].CurrentState)
	})

	if t.Failed() {
		t.FailNow()
	}

	// Pod UIDs before execute: the abort path applies the fenced CR and then
	// re-applies the initial CR, so the gateway must roll at least once.
	podUIDsBefore := getGatewayPodUIDs(t, clientset, cfg.Namespace, cfg.GatewayName)
	t.Logf("Gateway pods before execute: %d pods", len(podUIDsBefore))

	migrationID := readMigrationState(t, cfg, stateFile).Migrations[0].MigrationID
	executeArgs := []string{
		"migration", "execute",
		"--migration-id", migrationID,
		"--migration-state-file", stateFile,
		"--cluster-api-key", cfg.ClusterAPIKey,
		"--cluster-api-secret", cfg.ClusterAPISecret,
		"--lag-threshold", "0",
		"--use-unauthenticated-plaintext",
		"--insecure-skip-tls-verify",
		"--detect-unrouted-producers-duration", "10s",
	}

	// --- Phase A: rogue producer trips detection, fence rolls back ---
	t.Run("rogue_producer_trips_detection", func(t *testing.T) {
		// Writes directly to the source brokers, bypassing the gateway — the
		// exact condition detection exists to catch. Duration outlives the
		// fence rollout plus the monitoring window; cleanup below is the
		// backstop, and Phase B stops it explicitly before resuming.
		startProducerOnSource(t, cfg, 10*time.Minute)
		t.Cleanup(func() { stopProducer(t, cfg) })
		time.Sleep(2 * time.Second)

		stdout, stderr, err := runKCP(t, cfg, executeArgs...)
		t.Logf("execute stdout:\n%s", stdout)
		t.Logf("execute stderr:\n%s", stderr)
		combined := stdout + stderr

		require.Error(t, err, "execute must fail while a producer writes directly to the source cluster")
		assert.Contains(t, combined, "unrouted producer", "failure should identify unrouted producers")
		assert.Contains(t, combined, fmt.Sprintf("topic %s partition", cfg.TopicName),
			"violation should name the affected topic and partition")
		assert.Contains(t, combined, "Gateway unfenced", "rollback should report the gateway was unfenced")
		assert.NotContains(t, combined, "Promoting mirror topics",
			"promotion must never start when detection fires")

		state := readMigrationState(t, cfg, stateFile)
		require.Len(t, state.Migrations, 1)
		assert.Equal(t, "initialized", state.Migrations[0].CurrentState,
			"abort_fence should roll the FSM back to initialized")
	})

	if t.Failed() {
		t.FailNow()
	}

	// --- Verify the live Gateway CR was restored to the initial spec ---
	t.Run("verify_gateway_restored_to_initial", func(t *testing.T) {
		cr := getGatewayCR(t, dynClient, cfg.Namespace, cfg.GatewayName)

		spec, found, err := unstructured.NestedMap(cr.Object, "spec")
		require.NoError(t, err)
		require.True(t, found, "spec not found in Gateway CR")

		routes, found, err := unstructured.NestedSlice(spec, "routes")
		require.NoError(t, err)
		require.True(t, found, "routes not found in spec")
		require.Len(t, routes, 1)

		route, ok := routes[0].(map[string]interface{})
		require.True(t, ok, "expected route to be a map")
		_, hasFence := route["fence"]
		assert.False(t, hasFence, "restored initial CR must not have fence config")

		// Distinguishes "initial restored" from "accidentally switched over":
		// both lack a fence, but only the initial CR still points at source.
		streamingDomains, found, err := unstructured.NestedSlice(spec, "streamingDomains")
		require.NoError(t, err)
		require.True(t, found)
		require.Len(t, streamingDomains, 1)

		domain, ok := streamingDomains[0].(map[string]interface{})
		require.True(t, ok, "expected streaming domain to be a map")
		domainName, _, _ := unstructured.NestedString(domain, "name")
		assert.Equal(t, "source-kafka-cluster", domainName,
			"rollback must restore the initial CR pointing at source, not the switchover CR")
	})

	t.Run("verify_gateway_rolled_out_on_abort", func(t *testing.T) {
		podUIDsAfter := getGatewayPodUIDs(t, clientset, cfg.Namespace, cfg.GatewayName)
		t.Logf("Gateway pods after aborted execute: %d pods", len(podUIDsAfter))

		rolled := false
		for uid := range podUIDsAfter {
			if _, existed := podUIDsBefore[uid]; !existed {
				rolled = true
				break
			}
		}
		assert.True(t, rolled, "fence+unfence cycle should have rolled the gateway pods")
	})

	if t.Failed() {
		t.FailNow()
	}

	// --- Phase B: rogue producer stopped, resume completes ---
	t.Run("resume_after_stopping_rogue_producer", func(t *testing.T) {
		stopProducer(t, cfg)

		stdout, stderr, err := runKCP(t, cfg, executeArgs...)
		t.Logf("resume stdout:\n%s", stdout)
		t.Logf("resume stderr:\n%s", stderr)
		combined := stdout + stderr

		require.NoError(t, err, "execute should succeed once the rogue producer is stopped")
		assert.Contains(t, combined, "Checking for unrouted producers", "resume must re-run detection")
		assert.Contains(t, combined, "Source offsets stable", "detection should pass on a quiet source")

		state := readMigrationState(t, cfg, stateFile)
		require.Len(t, state.Migrations, 1)
		assert.Equal(t, "switched", state.Migrations[0].CurrentState)
	})

	if t.Failed() {
		t.FailNow()
	}

	// --- Verify the Gateway CR now matches the switchover spec ---
	t.Run("verify_gateway_switched_over", func(t *testing.T) {
		cr := getGatewayCR(t, dynClient, cfg.Namespace, cfg.GatewayName)

		spec, found, err := unstructured.NestedMap(cr.Object, "spec")
		require.NoError(t, err)
		require.True(t, found, "spec not found in Gateway CR")

		routes, found, err := unstructured.NestedSlice(spec, "routes")
		require.NoError(t, err)
		require.True(t, found, "routes not found in spec")
		require.Len(t, routes, 1)

		route, ok := routes[0].(map[string]interface{})
		require.True(t, ok, "expected route to be a map")
		_, hasFence := route["fence"]
		assert.False(t, hasFence, "switchover CR should not have fence config")

		streamingDomains, found, err := unstructured.NestedSlice(spec, "streamingDomains")
		require.NoError(t, err)
		require.True(t, found)
		require.Len(t, streamingDomains, 1)

		domain, ok := streamingDomains[0].(map[string]interface{})
		require.True(t, ok, "expected streaming domain to be a map")
		domainName, _, _ := unstructured.NestedString(domain, "name")
		assert.Equal(t, "destination-kafka-cluster", domainName,
			"switchover should point at the destination streaming domain")
	})
}

// TestMigrationE2E_RogueProducerFalsePositive asserts the inverse of
// TestMigrationE2E_RogueProducerDetection: with zero rogue producers — only a
// single legitimate producer sending continuously through the gateway's real
// proxy endpoint (not the raw source bootstrap) — detection must never fire.
//
// The gateway's fence CR rollout creates a new (correctly fenced) pod and only
// scales down the old (still-unfenced) one once the new pod passes its
// readiness probe. Until then, both pods are live behind the same Service, so
// the legitimate producer can keep landing writes on the source cluster
// through the old pod for tens of seconds after kcp reports "Gateway fenced
// and ready". detectUnroutedProducers' two-point source-offset comparison
// cannot distinguish that from an actual rogue producer.
//
// This test currently FAILS against the shipped detector: it documents the
// false positive so a fix has a concrete, automated target to turn green.
func TestMigrationE2E_RogueProducerFalsePositive(t *testing.T) {
	cfg := loadEnvConfig(t, scenarioRogueProducerFalsePositive)

	stateFile := "/workspace/migration-state-rogue-producer-false-positive.json"

	// --- Step 1: kcp migration init ---
	t.Run("init", func(t *testing.T) {
		initArgs := []string{
			"migration", "init",
			"--source-bootstrap", cfg.SourceBootstrap,
			"--cluster-bootstrap", cfg.DestBootstrap,
			"--cluster-id", cfg.DestClusterID,
			"--cluster-rest-endpoint", cfg.RestProxyEndpoint,
			"--cluster-link-name", cfg.ClusterLinkName,
			"--cluster-api-key", cfg.ClusterAPIKey,
			"--cluster-api-secret", cfg.ClusterAPISecret,
			"--k8s-namespace", cfg.Namespace,
			"--initial-cr-name", cfg.GatewayName,
			"--fenced-cr-yaml", cfg.FencedCR,
			"--switchover-cr-yaml", cfg.SwitchoverCR,
			"--migration-state-file", stateFile,
			"--use-unauthenticated-plaintext",
			"--kube-path", cfg.KubePath,
			"--insecure-skip-tls-verify",
		}

		stdout, stderr, err := runKCP(t, cfg, initArgs...)
		t.Logf("init stdout:\n%s", stdout)
		t.Logf("init stderr:\n%s", stderr)
		require.NoError(t, err, "kcp migration init failed")

		state := readMigrationState(t, cfg, stateFile)
		require.Len(t, state.Migrations, 1)
		assert.Equal(t, "initialized", state.Migrations[0].CurrentState)
	})

	if t.Failed() {
		t.FailNow()
	}

	migrationID := readMigrationState(t, cfg, stateFile).Migrations[0].MigrationID
	executeArgs := []string{
		"migration", "execute",
		"--migration-id", migrationID,
		"--migration-state-file", stateFile,
		"--cluster-api-key", cfg.ClusterAPIKey,
		"--cluster-api-secret", cfg.ClusterAPISecret,
		"--lag-threshold", "0",
		"--use-unauthenticated-plaintext",
		"--insecure-skip-tls-verify",
		"--detect-unrouted-producers-duration", "10s",
	}

	// --- Step 2: a legitimate, gateway-routed producer must not trip detection ---
	t.Run("legitimate_gateway_producer_must_not_trip_detection", func(t *testing.T) {
		// Runs continuously through the fence, the verify window, and promote —
		// outlives the whole execute call. No rogue (direct-to-source) producer
		// exists anywhere in this test.
		startProducerOnGateway(t, cfg, 3*time.Minute)
		t.Cleanup(func() { stopProducer(t, cfg) })
		time.Sleep(2 * time.Second)

		stdout, stderr, err := runKCP(t, cfg, executeArgs...)
		t.Logf("execute stdout:\n%s", stdout)
		t.Logf("execute stderr:\n%s", stderr)
		combined := stdout + stderr

		require.NoError(t, err,
			"execute must not fail when the only producer is legitimate, gateway-routed traffic")
		// Assert on the detection-failure message, not the substring "unrouted
		// producer": the normal "Checking for unrouted producers..." phase banner
		// and the "no unrouted producers detected" success line both contain it,
		// so only the failure path's "bypassing the gateway" phrase is a reliable
		// signal that a producer was wrongly flagged.
		assert.NotContains(t, combined, "bypassing the gateway",
			"a legitimate gateway-routed producer must never be reported as unrouted")
		assert.Contains(t, combined, "Source offsets stable",
			"detection should pass when no producer bypasses the gateway")

		state := readMigrationState(t, cfg, stateFile)
		require.Len(t, state.Migrations, 1)
		assert.Equal(t, "switched", state.Migrations[0].CurrentState)
	})
}

// TestMigrationE2E_PauseOffsetSync_RogueProducerRollback combines the pause
// flag with unrouted-producer detection: detection fires from the
// offset_sync_paused state, so the abort_fence rollback must not only unfence
// the gateway but also restore the paused consumer.offset.* config on the
// real cluster link — including consumer.offset.group.filters, which CP
// clears as a side effect of setting consumer.offset.sync.enable=false.
//
// Phase A: init with --pause-consumer-offset-sync, run execute with a rogue
// producer writing directly to source. The pause stage disables sync, then
// detection trips, and the rollback restores enable=true plus the filters and
// clears the flipped marker.
//
// Phase B: with the rogue producer stopped, re-running execute must pause
// AGAIN (the cleared marker makes the retry a fresh pause, not a skip),
// complete to switched, and restore the config at the end.
//
// Runs against the "pause-sync-rogue" scenario — its own dedicated source
// topic, cluster link, and gateway CR provisioned by setup.sh.
func TestMigrationE2E_PauseOffsetSync_RogueProducerRollback(t *testing.T) {
	cfg := loadEnvConfig(t, scenarioPauseSyncRogue)

	kubeConfig, err := clientcmd.NewNonInteractiveDeferredLoadingClientConfig(
		&clientcmd.ClientConfigLoadingRules{ExplicitPath: cfg.Kubeconfig},
		&clientcmd.ConfigOverrides{CurrentContext: cfg.KubeContext},
	).ClientConfig()
	require.NoError(t, err, "failed to build kubeconfig")

	dynClient, err := dynamic.NewForConfig(kubeConfig)
	require.NoError(t, err)

	stateFile := "/workspace/migration-state-pause-sync-rogue.json"
	stopProducer(t, cfg)

	const filtersKey = "consumer.offset.group.filters"
	const filtersValue = `{"groupFilters":[{"name":"e2e-*","patternType":"PREFIXED","filterType":"INCLUDE"}]}`

	// Filters set before init: the init snapshot captures them, the pause
	// stage's disable clears them (real CP side effect), and the ROLLBACK
	// restore — not the post-switchover one — must bring them back.
	setClusterLinkConfig(t, cfg, filtersKey, filtersValue)
	require.Equal(t, "true", getClusterLinkOffsetSyncEnable(t, cfg), "fixture must start with consumer.offset.sync.enable=true")
	require.Equal(t, filtersValue, getClusterLinkConfig(t, cfg, filtersKey), "fixture must have filters set before init")

	// --- Step 0: seed the source topic so the link has data to mirror ---
	t.Run("seed_source_topic", func(t *testing.T) {
		startProducerOnSource(t, cfg, 10*time.Second)
		time.Sleep(2 * time.Second)
		stopProducer(t, cfg)
	})

	// --- Step 1: init with the flag ---
	t.Run("init_with_flag", func(t *testing.T) {
		initArgs := []string{
			"migration", "init",
			"--source-bootstrap", cfg.SourceBootstrap,
			"--cluster-bootstrap", cfg.DestBootstrap,
			"--cluster-id", cfg.DestClusterID,
			"--cluster-rest-endpoint", cfg.RestProxyEndpoint,
			"--cluster-link-name", cfg.ClusterLinkName,
			"--cluster-api-key", cfg.ClusterAPIKey,
			"--cluster-api-secret", cfg.ClusterAPISecret,
			"--k8s-namespace", cfg.Namespace,
			"--initial-cr-name", cfg.GatewayName,
			"--fenced-cr-yaml", cfg.FencedCR,
			"--switchover-cr-yaml", cfg.SwitchoverCR,
			"--migration-state-file", stateFile,
			"--use-unauthenticated-plaintext",
			"--kube-path", cfg.KubePath,
			"--insecure-skip-tls-verify",
			"--pause-consumer-offset-sync",
		}

		stdout, stderr, err := runKCP(t, cfg, initArgs...)
		t.Logf("init stdout:\n%s", stdout)
		t.Logf("init stderr:\n%s", stderr)
		require.NoError(t, err, "kcp migration init failed")

		state := readMigrationState(t, cfg, stateFile)
		require.Len(t, state.Migrations, 1)
		assert.Equal(t, "initialized", state.Migrations[0].CurrentState)
		assert.True(t, state.Migrations[0].PauseConsumerOffsetSync, "intent must persist")
	})

	if t.Failed() {
		t.FailNow()
	}

	migrationID := readMigrationState(t, cfg, stateFile).Migrations[0].MigrationID
	executeArgs := []string{
		"migration", "execute",
		"--migration-id", migrationID,
		"--migration-state-file", stateFile,
		"--cluster-api-key", cfg.ClusterAPIKey,
		"--cluster-api-secret", cfg.ClusterAPISecret,
		"--lag-threshold", "0",
		"--use-unauthenticated-plaintext",
		"--insecure-skip-tls-verify",
		"--detect-unrouted-producers-duration", "10s",
	}

	// --- Phase A: detection fires after the pause, rollback restores sync ---
	t.Run("rollback_restores_sync_config", func(t *testing.T) {
		startProducerOnSource(t, cfg, 10*time.Minute)
		t.Cleanup(func() { stopProducer(t, cfg) })
		time.Sleep(2 * time.Second)

		stdout, stderr, err := runKCP(t, cfg, executeArgs...)
		t.Logf("execute stdout:\n%s", stdout)
		t.Logf("execute stderr:\n%s", stderr)
		combined := stdout + stderr

		require.Error(t, err, "execute must fail while a producer writes directly to the source cluster")

		// The pause stage ran before detection tripped...
		assert.Contains(t, combined, "Pausing consumer.offset.sync",
			"the pause stage must run before fence verification")
		assert.Contains(t, combined, "unrouted producer", "failure should identify unrouted producers")
		// ...and the rollback both unfenced and restored.
		assert.Contains(t, combined, "Unrouted producers detected",
			"the rollback banner must name detection as the reason")
		assert.Contains(t, combined, "Gateway unfenced", "rollback should report the gateway was unfenced")
		assert.Contains(t, combined, "Restoring consumer.offset.sync",
			"the rollback must run the sync-config restore after unfencing")
		assert.NotContains(t, combined, "Gateway unfenced but",
			"the restore must succeed — the soft-fail remediation note must not appear")
		assert.NotContains(t, combined, "Promoting mirror topics",
			"promotion must never start when detection fires")

		state := readMigrationState(t, cfg, stateFile)
		require.Len(t, state.Migrations, 1)
		assert.Equal(t, "initialized", state.Migrations[0].CurrentState,
			"abort_fence should roll the FSM back to initialized")
		assert.False(t, state.Migrations[0].PauseConsumerOffsetSyncFlipped,
			"the rollback restore must clear the flipped marker")
	})

	if t.Failed() {
		t.FailNow()
	}

	// --- Live cluster link restored by the rollback, not left paused ---
	t.Run("cluster_link_restored_after_rollback", func(t *testing.T) {
		assert.Equal(t, "true", getClusterLinkOffsetSyncEnable(t, cfg),
			"rollback must restore consumer.offset.sync.enable=true")
		assert.Equal(t, filtersValue, getClusterLinkConfig(t, cfg, filtersKey),
			"rollback must re-apply the filters that the pause cleared")
	})

	t.Run("gateway_restored_to_initial", func(t *testing.T) {
		assertGatewaySpec(t, dynClient, cfg.Namespace, cfg.GatewayName, "source-kafka-cluster")
	})

	if t.Failed() {
		t.FailNow()
	}

	// --- Phase B: rogue producer stopped, resume pauses again and completes ---
	t.Run("resume_pauses_again_and_completes", func(t *testing.T) {
		stopProducer(t, cfg)

		stdout, stderr, err := runKCP(t, cfg, executeArgs...)
		t.Logf("resume stdout:\n%s", stdout)
		t.Logf("resume stderr:\n%s", stderr)
		combined := stdout + stderr

		require.NoError(t, err, "execute should succeed once the rogue producer is stopped")
		assert.Contains(t, combined, "Pausing consumer.offset.sync",
			"the retry must pause afresh — the cleared marker means this is not a skip")
		assert.NotContains(t, combined, "already paused",
			"the retry must not take the already-flipped skip path")
		assert.Contains(t, combined, "Restoring consumer.offset.sync",
			"the post-switchover restore bookend must run")

		state := readMigrationState(t, cfg, stateFile)
		require.Len(t, state.Migrations, 1)
		assert.Equal(t, "switched", state.Migrations[0].CurrentState)
		assert.False(t, state.Migrations[0].PauseConsumerOffsetSyncFlipped, "marker must clear after successful restore")
	})

	if t.Failed() {
		t.FailNow()
	}

	t.Run("final_state_restored", func(t *testing.T) {
		assert.Equal(t, "true", getClusterLinkOffsetSyncEnable(t, cfg), "final toggle must be true")
		assert.Equal(t, filtersValue, getClusterLinkConfig(t, cfg, filtersKey), "final filters must match the pre-init value")
		assertGatewaySpec(t, dynClient, cfg.Namespace, cfg.GatewayName, "destination-kafka-cluster")
	})
}

// TestMigrationE2E_PauseOffsetSync_DriftRollsBackFence exercises the other
// abort_fence source state: a pause_offset_sync failure at fenced. Init
// passes (enable=true), then the config drifts to false externally before
// execute reaches the pause stage. The pause refuses to flip a link that is
// not in the expected state, and — because clients must not be held fenced
// over a config problem — the FSM rolls the fence back to initialized.
//
// The restore half of the rollback must be a NO-OP here: kcp never flipped
// anything, so the externally-set false must be left untouched.
//
// Phase B repairs the drift and re-runs execute to completion.
//
// Runs against the "pause-sync-drift" scenario — its own dedicated source
// topic, cluster link, and gateway CR provisioned by setup.sh — so flipping
// offset-sync to "false" does not leak into other tests.
func TestMigrationE2E_PauseOffsetSync_DriftRollsBackFence(t *testing.T) {
	cfg := loadEnvConfig(t, scenarioPauseSyncDrift)

	kubeConfig, err := clientcmd.NewNonInteractiveDeferredLoadingClientConfig(
		&clientcmd.ClientConfigLoadingRules{ExplicitPath: cfg.Kubeconfig},
		&clientcmd.ConfigOverrides{CurrentContext: cfg.KubeContext},
	).ClientConfig()
	require.NoError(t, err, "failed to build kubeconfig")

	dynClient, err := dynamic.NewForConfig(kubeConfig)
	require.NoError(t, err)

	stateFile := "/workspace/migration-state-pause-sync-drift.json"
	stopProducer(t, cfg)

	// Leave the shared fixture healthy whatever happens below.
	t.Cleanup(func() {
		setClusterLinkConfig(t, cfg, "consumer.offset.sync.enable", "true")
	})

	require.Equal(t, "true", getClusterLinkOffsetSyncEnable(t, cfg), "fixture must start with consumer.offset.sync.enable=true")

	// --- Step 0: seed the source topic so the link has data to mirror ---
	t.Run("seed_source_topic", func(t *testing.T) {
		startProducerOnSource(t, cfg, 10*time.Second)
		time.Sleep(2 * time.Second)
		stopProducer(t, cfg)
	})

	// --- Step 1: init with the flag (link is healthy, so init passes) ---
	t.Run("init_with_flag", func(t *testing.T) {
		initArgs := []string{
			"migration", "init",
			"--source-bootstrap", cfg.SourceBootstrap,
			"--cluster-bootstrap", cfg.DestBootstrap,
			"--cluster-id", cfg.DestClusterID,
			"--cluster-rest-endpoint", cfg.RestProxyEndpoint,
			"--cluster-link-name", cfg.ClusterLinkName,
			"--cluster-api-key", cfg.ClusterAPIKey,
			"--cluster-api-secret", cfg.ClusterAPISecret,
			"--k8s-namespace", cfg.Namespace,
			"--initial-cr-name", cfg.GatewayName,
			"--fenced-cr-yaml", cfg.FencedCR,
			"--switchover-cr-yaml", cfg.SwitchoverCR,
			"--migration-state-file", stateFile,
			"--use-unauthenticated-plaintext",
			"--kube-path", cfg.KubePath,
			"--insecure-skip-tls-verify",
			"--pause-consumer-offset-sync",
		}

		stdout, stderr, err := runKCP(t, cfg, initArgs...)
		t.Logf("init stdout:\n%s", stdout)
		t.Logf("init stderr:\n%s", stderr)
		require.NoError(t, err, "kcp migration init failed")

		state := readMigrationState(t, cfg, stateFile)
		require.Len(t, state.Migrations, 1)
		assert.Equal(t, "initialized", state.Migrations[0].CurrentState)
	})

	if t.Failed() {
		t.FailNow()
	}

	// --- Step 2: introduce drift AFTER init, BEFORE execute ---
	setClusterLinkConfig(t, cfg, "consumer.offset.sync.enable", "false")
	for i := 0; i < 10; i++ {
		if getClusterLinkOffsetSyncEnable(t, cfg) == "false" {
			break
		}
		time.Sleep(500 * time.Millisecond)
	}
	require.Equal(t, "false", getClusterLinkOffsetSyncEnable(t, cfg), "drift must be visible before execute runs")

	migrationID := readMigrationState(t, cfg, stateFile).Migrations[0].MigrationID
	executeArgs := []string{
		"migration", "execute",
		"--migration-id", migrationID,
		"--migration-state-file", stateFile,
		"--cluster-api-key", cfg.ClusterAPIKey,
		"--cluster-api-secret", cfg.ClusterAPISecret,
		"--lag-threshold", "0",
		"--use-unauthenticated-plaintext",
		"--insecure-skip-tls-verify",
		"--detect-unrouted-producers-duration", "10s",
	}

	// --- Phase A: pause refuses on drift, fence rolls back ---
	t.Run("pause_refusal_rolls_back_fence", func(t *testing.T) {
		stdout, stderr, err := runKCP(t, cfg, executeArgs...)
		t.Logf("execute stdout:\n%s", stdout)
		t.Logf("execute stderr:\n%s", stderr)
		combined := stdout + stderr

		require.Error(t, err, "execute must fail when the pause stage finds the link already disabled")
		assert.Contains(t, combined, "--pause-consumer-offset-sync refused",
			"the failure must be the pause stage's drift refusal")
		assert.Contains(t, combined, "Pausing consumer offset sync failed",
			"the rollback banner must name the pause failure as the reason")
		assert.Contains(t, combined, "Gateway unfenced", "rollback should report the gateway was unfenced")
		assert.NotContains(t, combined, "Restoring consumer.offset.sync",
			"nothing was flipped, so the rollback restore must be a no-op")
		assert.NotContains(t, combined, "still fenced",
			"the post-failure guidance must not claim the gateway is fenced after a successful rollback")

		state := readMigrationState(t, cfg, stateFile)
		require.Len(t, state.Migrations, 1)
		assert.Equal(t, "initialized", state.Migrations[0].CurrentState,
			"abort_fence should roll the FSM back to initialized")
		assert.False(t, state.Migrations[0].PauseConsumerOffsetSyncFlipped,
			"the refusal happens before AlterConfigs, so the marker must never flip")
	})

	if t.Failed() {
		t.FailNow()
	}

	// --- Externally-set config untouched, gateway back to initial ---
	t.Run("external_config_untouched", func(t *testing.T) {
		assert.Equal(t, "false", getClusterLinkOffsetSyncEnable(t, cfg),
			"kcp must not overwrite a value it did not set — the restore is owed nothing")
	})

	t.Run("gateway_restored_to_initial", func(t *testing.T) {
		assertGatewaySpec(t, dynClient, cfg.Namespace, cfg.GatewayName, "source-kafka-cluster")
	})

	if t.Failed() {
		t.FailNow()
	}

	// --- Phase B: repair the drift, resume completes ---
	t.Run("resume_after_repairing_drift", func(t *testing.T) {
		setClusterLinkConfig(t, cfg, "consumer.offset.sync.enable", "true")
		for i := 0; i < 10; i++ {
			if getClusterLinkOffsetSyncEnable(t, cfg) == "true" {
				break
			}
			time.Sleep(500 * time.Millisecond)
		}
		require.Equal(t, "true", getClusterLinkOffsetSyncEnable(t, cfg), "repair must be visible before resuming")

		stdout, stderr, err := runKCP(t, cfg, executeArgs...)
		t.Logf("resume stdout:\n%s", stdout)
		t.Logf("resume stderr:\n%s", stderr)
		combined := stdout + stderr

		require.NoError(t, err, "execute should succeed once the drift is repaired")
		assert.Contains(t, combined, "Pausing consumer.offset.sync", "the retry must run the pause stage")
		assert.Contains(t, combined, "Restoring consumer.offset.sync", "the post-switchover restore bookend must run")

		state := readMigrationState(t, cfg, stateFile)
		require.Len(t, state.Migrations, 1)
		assert.Equal(t, "switched", state.Migrations[0].CurrentState)
		assert.False(t, state.Migrations[0].PauseConsumerOffsetSyncFlipped, "marker must clear after successful restore")
	})

	if t.Failed() {
		t.FailNow()
	}

	t.Run("final_state_restored", func(t *testing.T) {
		assert.Equal(t, "true", getClusterLinkOffsetSyncEnable(t, cfg), "final toggle must be true")
		assertGatewaySpec(t, dynClient, cfg.Namespace, cfg.GatewayName, "destination-kafka-cluster")
	})
}
