package kafka_acls

import (
	"fmt"

	"github.com/confluentinc/kcp/internal/generators/create_asset/migrate_acls/kafka_acls"
	"github.com/confluentinc/kcp/internal/utils"
	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

var (
	clusterFile string
	outputDir   string
)

func NewConvertKafkaAclsCmd() *cobra.Command {
	aclsCmd := &cobra.Command{
		Use:           "kafka",
		Short:         "Convert Kafka ACLs to Confluent Cloud ACLs.",
		Long:          "Convert Kafka ACLs to Confluent Cloud ACLs as individual Terraform resources.",
		SilenceErrors: true,
		PreRunE:       preRunConvertKafkaAcls,
		RunE:          runConvertKafkaAcls,
	}

	groups := map[*pflag.FlagSet]string{}

	requiredFlags := pflag.NewFlagSet("required", pflag.ExitOnError)
	requiredFlags.SortFlags = false
	requiredFlags.StringVar(&clusterFile, "cluster-file", "", "The cluster scan JSON file generated by the 'kcp scan cluster' command")
	aclsCmd.Flags().AddFlagSet(requiredFlags)
	groups[requiredFlags] = "Required Flags"

	optionalFlags := pflag.NewFlagSet("optional", pflag.ExitOnError)
	optionalFlags.SortFlags = false
	optionalFlags.StringVar(&outputDir, "output-dir", "", "The directory where the Confluent Cloud Terraform ACL assets will be written to")
	aclsCmd.Flags().AddFlagSet(optionalFlags)
	groups[optionalFlags] = "Optional Flags"

	aclsCmd.SetUsageFunc(func(c *cobra.Command) error {
		fmt.Printf("%s\n\n", c.Short)

		flagOrder := []*pflag.FlagSet{requiredFlags, optionalFlags}
		groupNames := []string{"Required Flags", "Optional Flags"}

		for i, fs := range flagOrder {
			usage := fs.FlagUsages()
			if usage != "" {
				fmt.Printf("%s:\n%s\n", groupNames[i], usage)
			}
		}

		fmt.Println("All flags can be provided via environment variables (uppercase, with underscores).")

		return nil
	})

	aclsCmd.MarkFlagRequired("cluster-file")

	return aclsCmd
}

func preRunConvertKafkaAcls(cmd *cobra.Command, args []string) error {
	if err := utils.BindEnvToFlags(cmd); err != nil {
		return err
	}

	return nil
}

func runConvertKafkaAcls(cmd *cobra.Command, args []string) error {
	if err := kafka_acls.RunConvertKafkaAcls(clusterFile, outputDir); err != nil {
		return fmt.Errorf("failed to convert Kafka ACLs: %v", err)
	}

	return nil
}
