#
# Generated by TerraSnap - https://terrasnap.confluent.io
# Date: 16 Jun 25 06:19 UTC
#

module "confluent_cloud" {
  source = "./confluent_cloud/terraform"

  providers = {
    confluent = confluent
  }

  confluent_cloud_api_key          = var.confluent_cloud_api_key
  confluent_cloud_api_secret       = var.confluent_cloud_api_secret
  confluent_cloud_provider         = var.confluent_cloud_provider
  confluent_cloud_region           = var.confluent_cloud_region
  confluent_cloud_environment_name = var.confluent_cloud_environment_name
  confluent_cloud_cluster_name     = var.confluent_cloud_cluster_name
}

module "cluster_link" {
  source = "./cluster_link/terraform"

  confluent_cloud_cluster_id = module.confluent_cloud.confluent_cloud_cluster_id
  confluent_cloud_cluster_api_key = module.confluent_cloud.confluent_cloud_cluster_api_key
  confluent_cloud_cluster_api_secret = module.confluent_cloud.confluent_cloud_cluster_api_secret
  confluent_cloud_cluster_rest_endpoint = module.confluent_cloud.confluent_cloud_cluster_rest_endpoint

  msk_cluster_id = var.msk_cluster_id
  msk_bootstrap_servers = var.msk_cluster_bootstrap_brokers
  msk_sasl_scram_username = var.msk_sasl_scram_username
  msk_sasl_scram_password = var.msk_sasl_scram_password
}