// JAAS login config for the dest-basic broker's embedded Admin REST API.
// The realm name (KafkaRest) must match kafka.rest.authentication.realm.
KafkaRest {
    org.eclipse.jetty.security.jaas.spi.PropertyFileLoginModule required
    debug="true"
    file="/etc/kafka/rest-auth/rest-password.properties";
};
