package hcl

import (
	"fmt"
	"log/slog"
	"slices"
	"strings"

	"github.com/confluentinc/kcp/internal/services/hcl/confluent"
	"github.com/confluentinc/kcp/internal/services/hcl/hcltypes"
	"github.com/confluentinc/kcp/internal/types"
	"github.com/confluentinc/kcp/internal/utils"
	"github.com/hashicorp/hcl/v2/hclwrite"
	"github.com/zclconf/go-cty/cty"
)

// Confluent Cloud supported ACL resource types.
// Keys are lowercase to match against strings.ToLower(acl.ResourceType) for case-insensitive comparison.
// https://docs.confluent.io/cloud/current/security/access-control/acl.html#acl-resources-and-operations-for-ccloud-summary
var supportedACLResourceTypes = map[string]bool{
	"topic":           true,
	"group":           true,
	"cluster":         true,
	"transactionalid": true, // matches strings.ToLower("TransactionalId") — no underscore
}

type MigrationScriptsHCLService struct {
	// SchemaRegistryClusterID overrides the random placeholder ID in schema exporter resources.
	// When empty, a random 8-character string is generated.
	SchemaRegistryClusterID string
}

func NewMigrationScriptsHCLService() *MigrationScriptsHCLService {
	return &MigrationScriptsHCLService{}
}

// GenerateMirrorTopicsFiles emits the migrate-topics Terraform layout: one
// .tf file per topic plus shared providers.tf and variables.tf. Both --mode
// mirror and --mode new use this layout. The legacy name is preserved for
// wire-format compatibility; consider renaming to GenerateMigrateTopicsFiles.
//
// Filename collisions across sanitized topic names are surfaced as a hard
// error — auto-disambiguating would hide a real surprise from the user.
func (s *MigrationScriptsHCLService) GenerateMirrorTopicsFiles(request types.MirrorTopicsRequest) (hcltypes.MigrationScriptsTerraformProject, error) {
	if request.Mode != types.MigrateTopicsModeMirror && request.Mode != types.MigrateTopicsModeNew {
		return hcltypes.MigrationScriptsTerraformProject{}, fmt.Errorf("invalid mode: %q (values: %s, %s)", request.Mode, types.MigrateTopicsModeMirror, types.MigrateTopicsModeNew)
	}

	topics := topicsForRequest(request)

	perTopicFiles := make(map[string]string, len(topics))
	collisions := make(map[string][]string)
	for _, topic := range topics {
		filename := utils.FormatHclResourceName(topic.Name) + ".tf"
		if _, exists := perTopicFiles[filename]; exists {
			collisions[filename] = append(collisions[filename], topic.Name)
			continue
		}
		var content string
		switch request.Mode {
		case types.MigrateTopicsModeMirror:
			content = s.generateSingleMirrorTopicTf(topic.Name, request)
		case types.MigrateTopicsModeNew:
			content = newModeTopicHeader + s.generateSingleNewTopicTf(topic, request)
		}
		perTopicFiles[filename] = content
	}
	if len(collisions) > 0 {
		return hcltypes.MigrationScriptsTerraformProject{}, fmt.Errorf("filename collisions detected: %v — rename or exclude one of the colliding source topics", collisions)
	}

	folder := hcltypes.MigrationScriptsTerraformFolder{
		ProvidersTf:     s.generateProvidersTf(),
		VariablesTf:     s.generateMirrorTopicsVariablesTf(),
		AdditionalFiles: perTopicFiles,
	}
	return hcltypes.MigrationScriptsTerraformProject{
		Folders: []hcltypes.MigrationScriptsTerraformFolder{folder},
	}, nil
}

// CCSupportedTopicConfigsDocsURL is the canonical reference for the CC-supported
// topic-config allow-list used by --mode new. Surfaced to the user in both the
// per-topic file header and the CLI note so the choice of dropped configs is
// auditable from either artifact.
const CCSupportedTopicConfigsDocsURL = "https://docs.confluent.io/cloud/current/topics/manage.html#ak-topic-configurations-for-all-ccloud-cluster-types"

const newModeTopicHeader = `# Generated by kcp create-asset migrate-topics --mode new
# Note: Some source topic configs are not configurable on Confluent Cloud and were dropped.
# See ` + CCSupportedTopicConfigsDocsURL + `
# for the current list of CC-supported topic configs.
`

// generateSingleNewTopicTf renders one confluent_kafka_topic resource block.
// Source partitions and allow-listed configs are preserved; everything else
// (including replication.factor) is dropped via the allow-list filter.
func (s *MigrationScriptsHCLService) generateSingleNewTopicTf(topic types.TopicDetails, request types.MirrorTopicsRequest) string {
	f := hclwrite.NewEmptyFile()
	tfResourceName := utils.FormatHclResourceName(topic.Name)
	f.Body().AppendBlock(confluent.GenerateNewTopic(
		tfResourceName,
		topic.Name,
		topic.Partitions,
		topic.Configurations,
		request.TargetClusterId,
		request.TargetClusterRestEndpoint,
	))
	return string(f.Bytes())
}

// topicsForRequest reconciles the two topic carriers on MirrorTopicsRequest:
// the CLI populates Topics with full details; the UI populates only the
// names-only SelectedTopics. For mirror mode only names matter, so we fall
// back to building a name-only []TopicDetails from SelectedTopics when Topics
// is empty. New mode requires Topics and is validated upstream.
func topicsForRequest(request types.MirrorTopicsRequest) []types.TopicDetails {
	if len(request.Topics) > 0 {
		return request.Topics
	}
	out := make([]types.TopicDetails, len(request.SelectedTopics))
	for i, name := range request.SelectedTopics {
		out[i] = types.TopicDetails{Name: name}
	}
	return out
}

func (s *MigrationScriptsHCLService) GenerateMigrateAclsFiles(request types.MigrateAclsRequest) (hcltypes.TerraformFiles, error) {
	return hcltypes.TerraformFiles{
		PerPrincipalTf:   s.generatePerPrincipalACLsTf(request),
		ProvidersTf:      s.generateProvidersTf(),
		VariablesTf:      s.generateMigrateACLsVariablesTf(),
		InputsAutoTfvars: s.generateMigrateACLsInputsAutoTfvars(request),
	}, nil
}

func (s *MigrationScriptsHCLService) GenerateMigrateSchemasFiles(request types.MigrateSchemasRequest) (hcltypes.MigrationScriptsTerraformProject, error) {
	ms := hcltypes.MigrationScriptsTerraformProject{}
	folders := []hcltypes.MigrationScriptsTerraformFolder{}
	for _, schemaRegistry := range request.SchemaRegistries {
		if schemaRegistry.Migrate {
			folderName := utils.URLToFolderName(schemaRegistry.SourceURL)
			folder := hcltypes.MigrationScriptsTerraformFolder{
				Name:             folderName,
				MainTf:           s.generateMigrateSchemasMainTf(schemaRegistry),
				ProvidersTf:      s.generateMigrateSchemasProvidersTf(),
				VariablesTf:      s.generateMigrateSchemasVariablesTf(),
				InputsAutoTfvars: s.generateMigrateSchemasInputsAutoTfvars(request.ConfluentCloudSchemaRegistryURL, schemaRegistry),
			}

			folders = append(folders, folder)
		}
	}

	ms.Folders = folders

	return ms, nil
}

// generateMigrateConnectorsFiles supports an in-progress migrate-connectors flow
// that is not yet wired into the orchestrator.
//
//nolint:unused // pre-existing, not yet wired up; surfaced by new-from-rev after the hcltypes rename
func (s *MigrationScriptsHCLService) generateMigrateConnectorsFiles() (hcltypes.TerraformFiles, error) {
	return hcltypes.TerraformFiles{
		MainTf:      s.generateMigrateConnectorsMainTf(),
		ProvidersTf: s.generateProvidersTf(),
		VariablesTf: s.generateMigrateConnectorsVariablesTf(),
	}, nil
}

func (s *MigrationScriptsHCLService) generateProvidersTf() string {
	f := hclwrite.NewEmptyFile()
	rootBody := f.Body()

	terraformBlock := rootBody.AppendNewBlock("terraform", nil)
	terraformBody := terraformBlock.Body()

	requiredProvidersBlock := terraformBody.AppendNewBlock("required_providers", nil)
	requiredProvidersBody := requiredProvidersBlock.Body()

	requiredProvidersBody.SetAttributeRaw(confluent.GenerateRequiredProviderTokens())
	rootBody.AppendNewline()

	rootBody.AppendBlock(confluent.GenerateProviderBlock())
	rootBody.AppendNewline()

	return string(f.Bytes())
}

// ============================================================================
// Migrate Topics Generation Methods
// ============================================================================

// generateSingleMirrorTopicTf renders one mirror-topic resource block to a
// stand-alone .tf file contents. Per-topic files compose with the shared
// providers.tf / variables.tf to form a complete Terraform module.
func (s *MigrationScriptsHCLService) generateSingleMirrorTopicTf(topicName string, request types.MirrorTopicsRequest) string {
	f := hclwrite.NewEmptyFile()
	tfResourceName := utils.FormatHclResourceName(topicName)
	f.Body().AppendBlock(confluent.GenerateMirrorTopic(tfResourceName, topicName, request.ClusterLinkName, request.TargetClusterId, request.TargetClusterRestEndpoint))
	return string(f.Bytes())
}

func (s *MigrationScriptsHCLService) generateMirrorTopicsVariablesTf() string {
	f := hclwrite.NewEmptyFile()
	rootBody := f.Body()

	variables := []struct {
		name        string
		description string
		sensitive   bool
	}{
		{confluent.VarConfluentCloudAPIKey, "Confluent Cloud API Key", false},
		{confluent.VarConfluentCloudAPISecret, "Confluent Cloud API Secret", true},
		{"confluent_cloud_cluster_api_key", "Confluent Cloud cluster API key", false},
		{"confluent_cloud_cluster_api_secret", "Confluent Cloud cluster API secret", true},
	}

	for _, v := range variables {
		variableBlock := rootBody.AppendNewBlock("variable", []string{v.name})
		variableBody := variableBlock.Body()
		variableBody.SetAttributeRaw("type", utils.TokensForResourceReference("string"))
		if v.description != "" {
			variableBody.SetAttributeValue("description", cty.StringVal(v.description))
		}
		if v.sensitive {
			variableBody.SetAttributeValue("sensitive", cty.BoolVal(true))
		}
		rootBody.AppendNewline()
	}

	return string(f.Bytes())
}

// ============================================================================
// Migrate ACLs Generation Methods
// ============================================================================

func (s *MigrationScriptsHCLService) generatePerPrincipalACLsTf(request types.MigrateAclsRequest) map[string]string {
	result := make(map[string]string)

	for principal, acls := range request.AclsByPrincipal {
		f := hclwrite.NewEmptyFile()
		rootBody := f.Body()

		serviceAccountResourceName := utils.FormatHclResourceName(principal)
		rootBody.AppendUnstructuredTokens(utils.TokensForComment("// Migrated principal: " + principal))
		rootBody.AppendNewline()
		rootBody.AppendBlock(confluent.GenerateServiceAccount(serviceAccountResourceName, principal, "Service Account for "+principal, request.PreventDestroy))
		rootBody.AppendNewline()

		aclIndex := 0
		for _, acl := range acls {
			if !supportedACLResourceTypes[strings.ToLower(acl.ResourceType)] {
				slog.Warn("skipping unsupported Confluent Cloud ACL resource type", "resource_type", acl.ResourceType, "principal", principal)
				continue
			}

			operationSnake := utils.CamelToScreamingSnake(acl.Operation)
			resourceTypeSnake := utils.CamelToScreamingSnake(acl.ResourceType)
			patternTypeSnake := utils.CamelToScreamingSnake(acl.ResourcePatternType)
			permissionSnake := utils.CamelToScreamingSnake(acl.PermissionType)
			tfResourceName := utils.FormatHclResourceName(fmt.Sprintf("%s_%s_%s_%s_%d", principal, acl.PermissionType, acl.ResourceType, operationSnake, aclIndex))

			rootBody.AppendBlock(confluent.GenerateKafkaACL(
				tfResourceName,
				resourceTypeSnake,
				acl.ResourceName,
				patternTypeSnake,
				fmt.Sprintf("User:${confluent_service_account.%s.id}", serviceAccountResourceName),
				acl.Host,
				operationSnake,
				permissionSnake,
				"var.confluent_cloud_cluster_id",
				"var.confluent_cloud_cluster_rest_endpoint",
				"var.confluent_cloud_cluster_api_key",
				"var.confluent_cloud_cluster_api_secret",
				request.PreventDestroy,
			))
			rootBody.AppendNewline()
			aclIndex++
		}

		fileName := fmt.Sprintf("%s.tf", serviceAccountResourceName)
		result[fileName] = string(f.Bytes())
	}

	return result
}

func (s *MigrationScriptsHCLService) generateMigrateACLsVariablesTf() string {
	f := hclwrite.NewEmptyFile()
	rootBody := f.Body()

	variables := []struct {
		name        string
		description string
		sensitive   bool
	}{
		{confluent.VarConfluentCloudAPIKey, "Confluent Cloud API Key", false},
		{confluent.VarConfluentCloudAPISecret, "Confluent Cloud API Secret", true},
		{"confluent_cloud_cluster_id", "Confluent Cloud cluster ID", false},
		{"confluent_cloud_cluster_rest_endpoint", "Confluent Cloud cluster REST endpoint", false},
		{"confluent_cloud_cluster_api_key", "Confluent Cloud cluster API key", false},
		{"confluent_cloud_cluster_api_secret", "Confluent Cloud cluster API secret", true},
	}

	for _, v := range variables {
		variableBlock := rootBody.AppendNewBlock("variable", []string{v.name})
		variableBody := variableBlock.Body()
		variableBody.SetAttributeRaw("type", utils.TokensForResourceReference("string"))
		if v.description != "" {
			variableBody.SetAttributeValue("description", cty.StringVal(v.description))
		}
		if v.sensitive {
			variableBody.SetAttributeValue("sensitive", cty.BoolVal(true))
		}
		rootBody.AppendNewline()
	}

	return string(f.Bytes())
}

func (s *MigrationScriptsHCLService) generateMigrateACLsInputsAutoTfvars(request types.MigrateAclsRequest) string {
	f := hclwrite.NewEmptyFile()
	rootBody := f.Body()

	rootBody.SetAttributeValue("confluent_cloud_cluster_id", cty.StringVal(request.TargetClusterId))
	rootBody.SetAttributeValue("confluent_cloud_cluster_rest_endpoint", cty.StringVal(request.TargetClusterRestEndpoint))

	return string(f.Bytes())
}

// ============================================================================
// Migrate Connectors Generation Methods
// ============================================================================

func (s *MigrationScriptsHCLService) generateMigrateConnectorsMainTf() string {
	f := hclwrite.NewEmptyFile()
	// rootBody := f.Body()

	return string(f.Bytes())
}

func (s *MigrationScriptsHCLService) generateMigrateConnectorsVariablesTf() string {
	f := hclwrite.NewEmptyFile()
	// rootBody := f.Body()

	return string(f.Bytes())
}

// ============================================================================
// Migrate Glue Schemas Generation Methods
// ============================================================================

func (s *MigrationScriptsHCLService) GenerateMigrateGlueSchemasFiles(request types.MigrateGlueSchemasRequest) (hcltypes.MigrationScriptsTerraformProject, error) {
	ms := hcltypes.MigrationScriptsTerraformProject{}
	folders := []hcltypes.MigrationScriptsTerraformFolder{}

	for _, registry := range request.GlueRegistries {
		if !registry.Migrate || len(registry.Schemas) == 0 {
			continue
		}

		generatedFiles, err := confluent.GenerateGlueSchemaMigrationHCL(registry.Schemas)
		if err != nil {
			return hcltypes.MigrationScriptsTerraformProject{}, fmt.Errorf("failed to generate HCL for Glue registry %q: %w", registry.RegistryName, err)
		}
		folder := hcltypes.MigrationScriptsTerraformFolder{
			Name:             registry.RegistryName,
			ProvidersTf:      s.generateProvidersTf(),
			VariablesTf:      s.generateMigrateGlueSchemasVariablesTf(),
			InputsAutoTfvars: s.generateMigrateGlueSchemasInputsAutoTfvars(request.ConfluentCloudSchemaRegistryURL),
			AdditionalFiles:  generatedFiles,
		}

		folders = append(folders, folder)
	}

	ms.Folders = folders
	return ms, nil
}

func (s *MigrationScriptsHCLService) generateMigrateGlueSchemasVariablesTf() string {
	allVars := slices.Concat(confluent.ConfluentProviderVariables, confluent.GlueSchemaVariables)
	return GenerateVariablesTf(allVars)
}

func (s *MigrationScriptsHCLService) generateMigrateGlueSchemasInputsAutoTfvars(confluentCloudSchemaRegistryURL string) string {
	f := hclwrite.NewEmptyFile()
	rootBody := f.Body()

	rootBody.SetAttributeValue(confluent.VarConfluentCloudSchemaRegistryURL, cty.StringVal(confluentCloudSchemaRegistryURL))

	return string(f.Bytes())
}

// ============================================================================
// Migrate Schemas Generation Methods (Confluent Schema Exporter)
// ============================================================================

func (s *MigrationScriptsHCLService) generateMigrateSchemasMainTf(schemaRegistry types.SchemaRegistryExporterConfig) string {
	f := hclwrite.NewEmptyFile()
	rootBody := f.Body()

	rootBody.AppendBlock(confluent.GenerateSchemaExporter(schemaRegistry, s.SchemaRegistryClusterID))
	rootBody.AppendNewline()

	return string(f.Bytes())
}

func (s *MigrationScriptsHCLService) generateMigrateSchemasProvidersTf() string {
	f := hclwrite.NewEmptyFile()
	rootBody := f.Body()

	terraformBlock := rootBody.AppendNewBlock("terraform", nil)
	terraformBody := terraformBlock.Body()

	requiredProvidersBlock := terraformBody.AppendNewBlock("required_providers", nil)
	requiredProvidersBody := requiredProvidersBlock.Body()

	requiredProvidersBody.SetAttributeRaw(confluent.GenerateRequiredProviderTokens())
	rootBody.AppendNewline()

	rootBody.AppendBlock(confluent.GenerateProviderBlock())
	rootBody.AppendNewline()

	return string(f.Bytes())
}

func (s *MigrationScriptsHCLService) generateMigrateSchemasVariablesTf() string {
	allVars := slices.Concat(confluent.ConfluentProviderVariables, confluent.SchemaExporterVariables)
	return GenerateVariablesTf(allVars)
}

func (s *MigrationScriptsHCLService) generateMigrateSchemasInputsAutoTfvars(confluentCloudSchemaRegistryURL string, schemaRegistry types.SchemaRegistryExporterConfig) string {
	f := hclwrite.NewEmptyFile()
	rootBody := f.Body()

	// hard code :(
	rootBody.SetAttributeValue(confluent.VarSourceSchemaRegistryURL, cty.StringVal(schemaRegistry.SourceURL))
	rootBody.SetAttributeRaw(confluent.VarSubjects, utils.TokensForStringList(schemaRegistry.Subjects))
	rootBody.SetAttributeValue(confluent.VarConfluentCloudSchemaRegistryURL, cty.StringVal(confluentCloudSchemaRegistryURL))

	return string(f.Bytes())
}
